/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.api;

import com.nextop.ebay.client.ApiException;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for MarketingApiAdReportApi
 */
@Ignore
public class MarketingApiAdReportApiTest {

    private final MarketingApiAdReportApi api = new MarketingApiAdReportApi();

    
    /**
     * /ad_report/{report_id}
     *
     * This call downloads the report as specified by the &lt;b&gt;report_id&lt;/b&gt; path parameter.  &lt;br&gt;&lt;br&gt;Call &lt;a href&#x3D;\&quot;/api-docs/sell/marketing/resources/ad_report_task/methods/createReportTask\&quot; title&#x3D;\&quot;createReportTask API docs\&quot;&gt;createReportTask&lt;/a&gt; to schedule and generate a Promoted Listings report. All date values are returned in UTC format (&lt;code&gt;yyyy-MM-ddThh:mm:ss.sssZ&lt;/code&gt;).&lt;br/&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;b&gt;Note:&lt;/b&gt; The reporting of some data related to sales and ad-fees may require a 72-hour (&lt;b&gt;maximum&lt;/b&gt;) adjustment period which is often referred to as the &lt;i&gt;Reconciliation Period&lt;/i&gt;. Such adjustment periods should, on average, be minimal. However, at any given time, the &lt;b&gt;payments&lt;/b&gt; tab may be used to view those amounts that have actually been charged.&lt;/span&gt;
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getReportTest() throws ApiException {
        String reportId = null;
        Object response = api.getReport(reportId);

        // TODO: test validations
    }
    
}
