/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.Charity;
import com.nextop.ebay.client.model.ExtendedProducerResponsibility;
import com.nextop.ebay.client.model.ListingPolicies;
import com.nextop.ebay.client.model.PricingSummary;
import com.nextop.ebay.client.model.Tax;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for EbayOfferDetailsWithId
 */
public class EbayOfferDetailsWithIdTest {
    private final EbayOfferDetailsWithId model = new EbayOfferDetailsWithId();

    /**
     * Model tests for EbayOfferDetailsWithId
     */
    @Test
    public void testEbayOfferDetailsWithId() {
        // TODO: test EbayOfferDetailsWithId
    }

    /**
     * Test the property 'availableQuantity'
     */
    @Test
    public void availableQuantityTest() {
        // TODO: test availableQuantity
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    public void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'charity'
     */
    @Test
    public void charityTest() {
        // TODO: test charity
    }

    /**
     * Test the property 'extendedProducerResponsibility'
     */
    @Test
    public void extendedProducerResponsibilityTest() {
        // TODO: test extendedProducerResponsibility
    }

    /**
     * Test the property 'hideBuyerDetails'
     */
    @Test
    public void hideBuyerDetailsTest() {
        // TODO: test hideBuyerDetails
    }

    /**
     * Test the property 'includeCatalogProductDetails'
     */
    @Test
    public void includeCatalogProductDetailsTest() {
        // TODO: test includeCatalogProductDetails
    }

    /**
     * Test the property 'listingDescription'
     */
    @Test
    public void listingDescriptionTest() {
        // TODO: test listingDescription
    }

    /**
     * Test the property 'listingDuration'
     */
    @Test
    public void listingDurationTest() {
        // TODO: test listingDuration
    }

    /**
     * Test the property 'listingPolicies'
     */
    @Test
    public void listingPoliciesTest() {
        // TODO: test listingPolicies
    }

    /**
     * Test the property 'listingStartDate'
     */
    @Test
    public void listingStartDateTest() {
        // TODO: test listingStartDate
    }

    /**
     * Test the property 'lotSize'
     */
    @Test
    public void lotSizeTest() {
        // TODO: test lotSize
    }

    /**
     * Test the property 'merchantLocationKey'
     */
    @Test
    public void merchantLocationKeyTest() {
        // TODO: test merchantLocationKey
    }

    /**
     * Test the property 'pricingSummary'
     */
    @Test
    public void pricingSummaryTest() {
        // TODO: test pricingSummary
    }

    /**
     * Test the property 'quantityLimitPerBuyer'
     */
    @Test
    public void quantityLimitPerBuyerTest() {
        // TODO: test quantityLimitPerBuyer
    }

    /**
     * Test the property 'secondaryCategoryId'
     */
    @Test
    public void secondaryCategoryIdTest() {
        // TODO: test secondaryCategoryId
    }

    /**
     * Test the property 'storeCategoryNames'
     */
    @Test
    public void storeCategoryNamesTest() {
        // TODO: test storeCategoryNames
    }

    /**
     * Test the property 'tax'
     */
    @Test
    public void taxTest() {
        // TODO: test tax
    }

}
