/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.Availability;
import com.nextop.ebay.client.model.PackageWeightAndSize;
import com.nextop.ebay.client.model.Product;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for InventoryItemWithSkuLocale
 */
public class InventoryItemWithSkuLocaleTest {
    private final InventoryItemWithSkuLocale model = new InventoryItemWithSkuLocale();

    /**
     * Model tests for InventoryItemWithSkuLocale
     */
    @Test
    public void testInventoryItemWithSkuLocale() {
        // TODO: test InventoryItemWithSkuLocale
    }

    /**
     * Test the property 'availability'
     */
    @Test
    public void availabilityTest() {
        // TODO: test availability
    }

    /**
     * Test the property 'condition'
     */
    @Test
    public void conditionTest() {
        // TODO: test condition
    }

    /**
     * Test the property 'conditionDescription'
     */
    @Test
    public void conditionDescriptionTest() {
        // TODO: test conditionDescription
    }

    /**
     * Test the property 'locale'
     */
    @Test
    public void localeTest() {
        // TODO: test locale
    }

    /**
     * Test the property 'packageWeightAndSize'
     */
    @Test
    public void packageWeightAndSizeTest() {
        // TODO: test packageWeightAndSize
    }

    /**
     * Test the property 'product'
     */
    @Test
    public void productTest() {
        // TODO: test product
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

}
