/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.Error;
import com.nextop.ebay.client.model.ItemConditionPolicy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ItemConditionPolicyResponse
 */
public class ItemConditionPolicyResponseTest {
    private final ItemConditionPolicyResponse model = new ItemConditionPolicyResponse();

    /**
     * Model tests for ItemConditionPolicyResponse
     */
    @Test
    public void testItemConditionPolicyResponse() {
        // TODO: test ItemConditionPolicyResponse
    }

    /**
     * Test the property 'itemConditionPolicies'
     */
    @Test
    public void itemConditionPoliciesTest() {
        // TODO: test itemConditionPolicies
    }

    /**
     * Test the property 'warnings'
     */
    @Test
    public void warningsTest() {
        // TODO: test warnings
    }

}
