/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.Amount;
import com.nextop.ebay.client.model.AppliedPromotion;
import com.nextop.ebay.client.model.DeliveryCost;
import com.nextop.ebay.client.model.EbayCollectAndRemitTax;
import com.nextop.ebay.client.model.GiftDetails;
import com.nextop.ebay.client.model.ItemLocation;
import com.nextop.ebay.client.model.LineItemFulfillmentInstructions;
import com.nextop.ebay.client.model.LineItemProperties;
import com.nextop.ebay.client.model.LineItemRefund;
import com.nextop.ebay.client.model.Tax;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for LineItem
 */
public class LineItemTest {
    private final LineItem model = new LineItem();

    /**
     * Model tests for LineItem
     */
    @Test
    public void testLineItem() {
        // TODO: test LineItem
    }

    /**
     * Test the property 'appliedPromotions'
     */
    @Test
    public void appliedPromotionsTest() {
        // TODO: test appliedPromotions
    }

    /**
     * Test the property 'deliveryCost'
     */
    @Test
    public void deliveryCostTest() {
        // TODO: test deliveryCost
    }

    /**
     * Test the property 'discountedLineItemCost'
     */
    @Test
    public void discountedLineItemCostTest() {
        // TODO: test discountedLineItemCost
    }

    /**
     * Test the property 'ebayCollectAndRemitTaxes'
     */
    @Test
    public void ebayCollectAndRemitTaxesTest() {
        // TODO: test ebayCollectAndRemitTaxes
    }

    /**
     * Test the property 'giftDetails'
     */
    @Test
    public void giftDetailsTest() {
        // TODO: test giftDetails
    }

    /**
     * Test the property 'itemLocation'
     */
    @Test
    public void itemLocationTest() {
        // TODO: test itemLocation
    }

    /**
     * Test the property 'legacyItemId'
     */
    @Test
    public void legacyItemIdTest() {
        // TODO: test legacyItemId
    }

    /**
     * Test the property 'legacyVariationId'
     */
    @Test
    public void legacyVariationIdTest() {
        // TODO: test legacyVariationId
    }

    /**
     * Test the property 'lineItemCost'
     */
    @Test
    public void lineItemCostTest() {
        // TODO: test lineItemCost
    }

    /**
     * Test the property 'lineItemFulfillmentInstructions'
     */
    @Test
    public void lineItemFulfillmentInstructionsTest() {
        // TODO: test lineItemFulfillmentInstructions
    }

    /**
     * Test the property 'lineItemFulfillmentStatus'
     */
    @Test
    public void lineItemFulfillmentStatusTest() {
        // TODO: test lineItemFulfillmentStatus
    }

    /**
     * Test the property 'lineItemId'
     */
    @Test
    public void lineItemIdTest() {
        // TODO: test lineItemId
    }

    /**
     * Test the property 'listingMarketplaceId'
     */
    @Test
    public void listingMarketplaceIdTest() {
        // TODO: test listingMarketplaceId
    }

    /**
     * Test the property 'properties'
     */
    @Test
    public void propertiesTest() {
        // TODO: test properties
    }

    /**
     * Test the property 'purchaseMarketplaceId'
     */
    @Test
    public void purchaseMarketplaceIdTest() {
        // TODO: test purchaseMarketplaceId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'refunds'
     */
    @Test
    public void refundsTest() {
        // TODO: test refunds
    }

    /**
     * Test the property 'sku'
     */
    @Test
    public void skuTest() {
        // TODO: test sku
    }

    /**
     * Test the property 'soldFormat'
     */
    @Test
    public void soldFormatTest() {
        // TODO: test soldFormat
    }

    /**
     * Test the property 'taxes'
     */
    @Test
    public void taxesTest() {
        // TODO: test taxes
    }

    /**
     * Test the property 'title'
     */
    @Test
    public void titleTest() {
        // TODO: test title
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
