/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.BestOffer;
import com.nextop.ebay.client.model.ShippingCostOverride;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ListingPolicies
 */
public class ListingPoliciesTest {
    private final ListingPolicies model = new ListingPolicies();

    /**
     * Model tests for ListingPolicies
     */
    @Test
    public void testListingPolicies() {
        // TODO: test ListingPolicies
    }

    /**
     * Test the property 'bestOfferTerms'
     */
    @Test
    public void bestOfferTermsTest() {
        // TODO: test bestOfferTerms
    }

    /**
     * Test the property 'eBayPlusIfEligible'
     */
    @Test
    public void eBayPlusIfEligibleTest() {
        // TODO: test eBayPlusIfEligible
    }

    /**
     * Test the property 'fulfillmentPolicyId'
     */
    @Test
    public void fulfillmentPolicyIdTest() {
        // TODO: test fulfillmentPolicyId
    }

    /**
     * Test the property 'paymentPolicyId'
     */
    @Test
    public void paymentPolicyIdTest() {
        // TODO: test paymentPolicyId
    }

    /**
     * Test the property 'productCompliancePolicyIds'
     */
    @Test
    public void productCompliancePolicyIdsTest() {
        // TODO: test productCompliancePolicyIds
    }

    /**
     * Test the property 'returnPolicyId'
     */
    @Test
    public void returnPolicyIdTest() {
        // TODO: test returnPolicyId
    }

    /**
     * Test the property 'shippingCostOverrides'
     */
    @Test
    public void shippingCostOverridesTest() {
        // TODO: test shippingCostOverrides
    }

    /**
     * Test the property 'takeBackPolicyId'
     */
    @Test
    public void takeBackPolicyIdTest() {
        // TODO: test takeBackPolicyId
    }

}
