/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.AdditionalOption;
import com.nextop.ebay.client.model.Amount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for PurchasedRate
 */
public class PurchasedRateTest {
    private final PurchasedRate model = new PurchasedRate();

    /**
     * Model tests for PurchasedRate
     */
    @Test
    public void testPurchasedRate() {
        // TODO: test PurchasedRate
    }

    /**
     * Test the property 'additionalOptions'
     */
    @Test
    public void additionalOptionsTest() {
        // TODO: test additionalOptions
    }

    /**
     * Test the property 'baseShippingCost'
     */
    @Test
    public void baseShippingCostTest() {
        // TODO: test baseShippingCost
    }

    /**
     * Test the property 'destinationTimeZone'
     */
    @Test
    public void destinationTimeZoneTest() {
        // TODO: test destinationTimeZone
    }

    /**
     * Test the property 'maxEstimatedDeliveryDate'
     */
    @Test
    public void maxEstimatedDeliveryDateTest() {
        // TODO: test maxEstimatedDeliveryDate
    }

    /**
     * Test the property 'minEstimatedDeliveryDate'
     */
    @Test
    public void minEstimatedDeliveryDateTest() {
        // TODO: test minEstimatedDeliveryDate
    }

    /**
     * Test the property 'pickupNetworks'
     */
    @Test
    public void pickupNetworksTest() {
        // TODO: test pickupNetworks
    }

    /**
     * Test the property 'pickupSlotId'
     */
    @Test
    public void pickupSlotIdTest() {
        // TODO: test pickupSlotId
    }

    /**
     * Test the property 'pickupType'
     */
    @Test
    public void pickupTypeTest() {
        // TODO: test pickupType
    }

    /**
     * Test the property 'rateId'
     */
    @Test
    public void rateIdTest() {
        // TODO: test rateId
    }

    /**
     * Test the property 'shippingCarrierCode'
     */
    @Test
    public void shippingCarrierCodeTest() {
        // TODO: test shippingCarrierCode
    }

    /**
     * Test the property 'shippingCarrierName'
     */
    @Test
    public void shippingCarrierNameTest() {
        // TODO: test shippingCarrierName
    }

    /**
     * Test the property 'shippingQuoteId'
     */
    @Test
    public void shippingQuoteIdTest() {
        // TODO: test shippingQuoteId
    }

    /**
     * Test the property 'shippingServiceCode'
     */
    @Test
    public void shippingServiceCodeTest() {
        // TODO: test shippingServiceCode
    }

    /**
     * Test the property 'shippingServiceName'
     */
    @Test
    public void shippingServiceNameTest() {
        // TODO: test shippingServiceName
    }

    /**
     * Test the property 'totalShippingCost'
     */
    @Test
    public void totalShippingCostTest() {
        // TODO: test totalShippingCost
    }

}
