/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SalesTaxJurisdiction
 */
public class SalesTaxJurisdictionTest {
    private final SalesTaxJurisdiction model = new SalesTaxJurisdiction();

    /**
     * Model tests for SalesTaxJurisdiction
     */
    @Test
    public void testSalesTaxJurisdiction() {
        // TODO: test SalesTaxJurisdiction
    }

    /**
     * Test the property 'salesTaxJurisdictionId'
     */
    @Test
    public void salesTaxJurisdictionIdTest() {
        // TODO: test salesTaxJurisdictionId
    }

}
