/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.Amount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for SelectionRule
 */
public class SelectionRuleTest {
    private final SelectionRule model = new SelectionRule();

    /**
     * Model tests for SelectionRule
     */
    @Test
    public void testSelectionRule() {
        // TODO: test SelectionRule
    }

    /**
     * Test the property 'brands'
     */
    @Test
    public void brandsTest() {
        // TODO: test brands
    }

    /**
     * Test the property 'categoryIds'
     */
    @Test
    public void categoryIdsTest() {
        // TODO: test categoryIds
    }

    /**
     * Test the property 'categoryScope'
     */
    @Test
    public void categoryScopeTest() {
        // TODO: test categoryScope
    }

    /**
     * Test the property 'listingConditionIds'
     */
    @Test
    public void listingConditionIdsTest() {
        // TODO: test listingConditionIds
    }

    /**
     * Test the property 'maxPrice'
     */
    @Test
    public void maxPriceTest() {
        // TODO: test maxPrice
    }

    /**
     * Test the property 'minPrice'
     */
    @Test
    public void minPriceTest() {
        // TODO: test minPrice
    }

}
