/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.Amount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for TransactionSummaryResponse
 */
public class TransactionSummaryResponseTest {
    private final TransactionSummaryResponse model = new TransactionSummaryResponse();

    /**
     * Model tests for TransactionSummaryResponse
     */
    @Test
    public void testTransactionSummaryResponse() {
        // TODO: test TransactionSummaryResponse
    }

    /**
     * Test the property 'adjustmentAmount'
     */
    @Test
    public void adjustmentAmountTest() {
        // TODO: test adjustmentAmount
    }

    /**
     * Test the property 'adjustmentBookingEntry'
     */
    @Test
    public void adjustmentBookingEntryTest() {
        // TODO: test adjustmentBookingEntry
    }

    /**
     * Test the property 'adjustmentCount'
     */
    @Test
    public void adjustmentCountTest() {
        // TODO: test adjustmentCount
    }

    /**
     * Test the property 'balanceTransferAmount'
     */
    @Test
    public void balanceTransferAmountTest() {
        // TODO: test balanceTransferAmount
    }

    /**
     * Test the property 'balanceTransferBookingEntry'
     */
    @Test
    public void balanceTransferBookingEntryTest() {
        // TODO: test balanceTransferBookingEntry
    }

    /**
     * Test the property 'balanceTransferCount'
     */
    @Test
    public void balanceTransferCountTest() {
        // TODO: test balanceTransferCount
    }

    /**
     * Test the property 'creditAmount'
     */
    @Test
    public void creditAmountTest() {
        // TODO: test creditAmount
    }

    /**
     * Test the property 'creditBookingEntry'
     */
    @Test
    public void creditBookingEntryTest() {
        // TODO: test creditBookingEntry
    }

    /**
     * Test the property 'creditCount'
     */
    @Test
    public void creditCountTest() {
        // TODO: test creditCount
    }

    /**
     * Test the property 'disputeAmount'
     */
    @Test
    public void disputeAmountTest() {
        // TODO: test disputeAmount
    }

    /**
     * Test the property 'disputeBookingEntry'
     */
    @Test
    public void disputeBookingEntryTest() {
        // TODO: test disputeBookingEntry
    }

    /**
     * Test the property 'disputeCount'
     */
    @Test
    public void disputeCountTest() {
        // TODO: test disputeCount
    }

    /**
     * Test the property 'nonSaleChargeAmount'
     */
    @Test
    public void nonSaleChargeAmountTest() {
        // TODO: test nonSaleChargeAmount
    }

    /**
     * Test the property 'nonSaleChargeBookingEntry'
     */
    @Test
    public void nonSaleChargeBookingEntryTest() {
        // TODO: test nonSaleChargeBookingEntry
    }

    /**
     * Test the property 'nonSaleChargeCount'
     */
    @Test
    public void nonSaleChargeCountTest() {
        // TODO: test nonSaleChargeCount
    }

    /**
     * Test the property 'onHoldAmount'
     */
    @Test
    public void onHoldAmountTest() {
        // TODO: test onHoldAmount
    }

    /**
     * Test the property 'onHoldBookingEntry'
     */
    @Test
    public void onHoldBookingEntryTest() {
        // TODO: test onHoldBookingEntry
    }

    /**
     * Test the property 'onHoldCount'
     */
    @Test
    public void onHoldCountTest() {
        // TODO: test onHoldCount
    }

    /**
     * Test the property 'refundAmount'
     */
    @Test
    public void refundAmountTest() {
        // TODO: test refundAmount
    }

    /**
     * Test the property 'refundBookingEntry'
     */
    @Test
    public void refundBookingEntryTest() {
        // TODO: test refundBookingEntry
    }

    /**
     * Test the property 'refundCount'
     */
    @Test
    public void refundCountTest() {
        // TODO: test refundCount
    }

    /**
     * Test the property 'shippingLabelAmount'
     */
    @Test
    public void shippingLabelAmountTest() {
        // TODO: test shippingLabelAmount
    }

    /**
     * Test the property 'shippingLabelBookingEntry'
     */
    @Test
    public void shippingLabelBookingEntryTest() {
        // TODO: test shippingLabelBookingEntry
    }

    /**
     * Test the property 'shippingLabelCount'
     */
    @Test
    public void shippingLabelCountTest() {
        // TODO: test shippingLabelCount
    }

    /**
     * Test the property 'transferAmount'
     */
    @Test
    public void transferAmountTest() {
        // TODO: test transferAmount
    }

    /**
     * Test the property 'transferBookingEntry'
     */
    @Test
    public void transferBookingEntryTest() {
        // TODO: test transferBookingEntry
    }

    /**
     * Test the property 'transferCount'
     */
    @Test
    public void transferCountTest() {
        // TODO: test transferCount
    }

    /**
     * Test the property 'withdrawalAmount'
     */
    @Test
    public void withdrawalAmountTest() {
        // TODO: test withdrawalAmount
    }

    /**
     * Test the property 'withdrawalBookingEntry'
     */
    @Test
    public void withdrawalBookingEntryTest() {
        // TODO: test withdrawalBookingEntry
    }

    /**
     * Test the property 'withdrawalCount'
     */
    @Test
    public void withdrawalCountTest() {
        // TODO: test withdrawalCount
    }

}
