/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.Amount;
import com.nextop.ebay.client.model.Buyer;
import com.nextop.ebay.client.model.FeeJurisdiction;
import com.nextop.ebay.client.model.OrderLineItem;
import com.nextop.ebay.client.model.Reference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Transaction
 */
public class TransactionTest {
    private final Transaction model = new Transaction();

    /**
     * Model tests for Transaction
     */
    @Test
    public void testTransaction() {
        // TODO: test Transaction
    }

    /**
     * Test the property 'amount'
     */
    @Test
    public void amountTest() {
        // TODO: test amount
    }

    /**
     * Test the property 'bookingEntry'
     */
    @Test
    public void bookingEntryTest() {
        // TODO: test bookingEntry
    }

    /**
     * Test the property 'buyer'
     */
    @Test
    public void buyerTest() {
        // TODO: test buyer
    }

    /**
     * Test the property 'feeJurisdiction'
     */
    @Test
    public void feeJurisdictionTest() {
        // TODO: test feeJurisdiction
    }

    /**
     * Test the property 'feeType'
     */
    @Test
    public void feeTypeTest() {
        // TODO: test feeType
    }

    /**
     * Test the property 'orderId'
     */
    @Test
    public void orderIdTest() {
        // TODO: test orderId
    }

    /**
     * Test the property 'orderLineItems'
     */
    @Test
    public void orderLineItemsTest() {
        // TODO: test orderLineItems
    }

    /**
     * Test the property 'paymentsEntity'
     */
    @Test
    public void paymentsEntityTest() {
        // TODO: test paymentsEntity
    }

    /**
     * Test the property 'payoutId'
     */
    @Test
    public void payoutIdTest() {
        // TODO: test payoutId
    }

    /**
     * Test the property 'references'
     */
    @Test
    public void referencesTest() {
        // TODO: test references
    }

    /**
     * Test the property 'salesRecordReference'
     */
    @Test
    public void salesRecordReferenceTest() {
        // TODO: test salesRecordReference
    }

    /**
     * Test the property 'totalFeeAmount'
     */
    @Test
    public void totalFeeAmountTest() {
        // TODO: test totalFeeAmount
    }

    /**
     * Test the property 'totalFeeBasisAmount'
     */
    @Test
    public void totalFeeBasisAmountTest() {
        // TODO: test totalFeeBasisAmount
    }

    /**
     * Test the property 'transactionDate'
     */
    @Test
    public void transactionDateTest() {
        // TODO: test transactionDate
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

    /**
     * Test the property 'transactionMemo'
     */
    @Test
    public void transactionMemoTest() {
        // TODO: test transactionMemo
    }

    /**
     * Test the property 'transactionStatus'
     */
    @Test
    public void transactionStatusTest() {
        // TODO: test transactionStatus
    }

    /**
     * Test the property 'transactionType'
     */
    @Test
    public void transactionTypeTest() {
        // TODO: test transactionType
    }

}
