/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.AdUpdateStatusResponse;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * A type that defines the fields for the updated ad status in the bulk response.
 */
@ApiModel(description = "A type that defines the fields for the updated ad status in the bulk response.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class BulkAdUpdateStatusResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_RESPONSES = "responses";
  @SerializedName(SERIALIZED_NAME_RESPONSES)
  private List<AdUpdateStatusResponse> responses = null;


  public BulkAdUpdateStatusResponse responses(List<AdUpdateStatusResponse> responses) {
    
    this.responses = responses;
    return this;
  }

  public BulkAdUpdateStatusResponse addResponsesItem(AdUpdateStatusResponse responsesItem) {
    if (this.responses == null) {
      this.responses = new ArrayList<AdUpdateStatusResponse>();
    }
    this.responses.add(responsesItem);
    return this;
  }

   /**
   * An array of processed ad listings in bulk.
   * @return responses
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "An array of processed ad listings in bulk.")

  public List<AdUpdateStatusResponse> getResponses() {
    return responses;
  }


  public void setResponses(List<AdUpdateStatusResponse> responses) {
    this.responses = responses;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BulkAdUpdateStatusResponse bulkAdUpdateStatusResponse = (BulkAdUpdateStatusResponse) o;
    return Objects.equals(this.responses, bulkAdUpdateStatusResponse.responses);
  }

  @Override
  public int hashCode() {
    return Objects.hash(responses);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BulkAdUpdateStatusResponse {\n");
    sb.append("    responses: ").append(toIndentedString(responses)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

