/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * This container defines a coded coupon promotion. It is required if the promotion type is CODED_COUPON.
 */
@ApiModel(description = "This container defines a coded coupon promotion. It is required if the promotion type is CODED_COUPON.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class CouponConfiguration implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_COUPON_CODE = "couponCode";
  @SerializedName(SERIALIZED_NAME_COUPON_CODE)
  private String couponCode;

  public static final String SERIALIZED_NAME_COUPON_TYPE = "couponType";
  @SerializedName(SERIALIZED_NAME_COUPON_TYPE)
  private String couponType;

  public static final String SERIALIZED_NAME_MAX_COUPON_REDEMPTION_PER_USER = "maxCouponRedemptionPerUser";
  @SerializedName(SERIALIZED_NAME_MAX_COUPON_REDEMPTION_PER_USER)
  private Integer maxCouponRedemptionPerUser;


  public CouponConfiguration couponCode(String couponCode) {
    
    this.couponCode = couponCode;
    return this;
  }

   /**
   * A unique code that buyers can use during checkout to receive a discount. The code must be unique across eBay. &lt;br&gt;&lt;br&gt;The code must be from 8-15 alphanumeric characters and can contain no more than two dashes ( - ).&lt;br&gt;&lt;br&gt;This is required when the promotion type is CODED_COUPON.
   * @return couponCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A unique code that buyers can use during checkout to receive a discount. The code must be unique across eBay. <br><br>The code must be from 8-15 alphanumeric characters and can contain no more than two dashes ( - ).<br><br>This is required when the promotion type is CODED_COUPON.")

  public String getCouponCode() {
    return couponCode;
  }


  public void setCouponCode(String couponCode) {
    this.couponCode = couponCode;
  }


  public CouponConfiguration couponType(String couponType) {
    
    this.couponType = couponType;
    return this;
  }

   /**
   * This indicates the type of Coded Coupon promotion, and is required when the promotion type is &lt;b&gt;CODED_COUPON&lt;/b&gt;.&lt;br&gt;&lt;br&gt;Supported types:&lt;ul&gt;&lt;li&gt;&lt;b&gt;PRIVATE_SINGLE_SELLER_COUPON:&lt;/b&gt; Anyone can use and share the coupon code, but it isn&#39;t posted on eBay.&lt;/li&gt;&lt;li&gt;&lt;b&gt;PUBLIC_SINGLE_SELLER_COUPON:&lt;/b&gt; Anyone can find the coupon code on eBay and use it.&lt;/li&gt;&lt;/ul&gt; For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/marketing/types/sme:CouponTypeEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return couponType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This indicates the type of Coded Coupon promotion, and is required when the promotion type is <b>CODED_COUPON</b>.<br><br>Supported types:<ul><li><b>PRIVATE_SINGLE_SELLER_COUPON:</b> Anyone can use and share the coupon code, but it isn't posted on eBay.</li><li><b>PUBLIC_SINGLE_SELLER_COUPON:</b> Anyone can find the coupon code on eBay and use it.</li></ul> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/marketing/types/sme:CouponTypeEnum'>eBay API documentation</a>")

  public String getCouponType() {
    return couponType;
  }


  public void setCouponType(String couponType) {
    this.couponType = couponType;
  }


  public CouponConfiguration maxCouponRedemptionPerUser(Integer maxCouponRedemptionPerUser) {
    
    this.maxCouponRedemptionPerUser = maxCouponRedemptionPerUser;
    return this;
  }

   /**
   * This sets the limit on the number of times a buyer can use this coupon. The range of values is 1-10. If no value is provided, a buyer can use the coupon an unlimited number of times.
   * @return maxCouponRedemptionPerUser
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This sets the limit on the number of times a buyer can use this coupon. The range of values is 1-10. If no value is provided, a buyer can use the coupon an unlimited number of times.")

  public Integer getMaxCouponRedemptionPerUser() {
    return maxCouponRedemptionPerUser;
  }


  public void setMaxCouponRedemptionPerUser(Integer maxCouponRedemptionPerUser) {
    this.maxCouponRedemptionPerUser = maxCouponRedemptionPerUser;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CouponConfiguration couponConfiguration = (CouponConfiguration) o;
    return Objects.equals(this.couponCode, couponConfiguration.couponCode) &&
        Objects.equals(this.couponType, couponConfiguration.couponType) &&
        Objects.equals(this.maxCouponRedemptionPerUser, couponConfiguration.maxCouponRedemptionPerUser);
  }

  @Override
  public int hashCode() {
    return Objects.hash(couponCode, couponType, maxCouponRedemptionPerUser);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CouponConfiguration {\n");
    sb.append("    couponCode: ").append(toIndentedString(couponCode)).append("\n");
    sb.append("    couponType: ").append(toIndentedString(couponType)).append("\n");
    sb.append("    maxCouponRedemptionPerUser: ").append(toIndentedString(maxCouponRedemptionPerUser)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

