/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.AdReference;
import com.nextop.ebay.client.model.Error;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * This type defines the fields returned when you create an ad by inventory reference ID.
 */
@ApiModel(description = "This type defines the fields returned when you create an ad by inventory reference ID.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class CreateAdsByInventoryReferenceResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_AD_GROUP_ID = "adGroupId";
  @SerializedName(SERIALIZED_NAME_AD_GROUP_ID)
  private String adGroupId;

  public static final String SERIALIZED_NAME_ADS = "ads";
  @SerializedName(SERIALIZED_NAME_ADS)
  private List<AdReference> ads = null;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<Error> errors = null;

  public static final String SERIALIZED_NAME_INVENTORY_REFERENCE_ID = "inventoryReferenceId";
  @SerializedName(SERIALIZED_NAME_INVENTORY_REFERENCE_ID)
  private String inventoryReferenceId;

  public static final String SERIALIZED_NAME_INVENTORY_REFERENCE_TYPE = "inventoryReferenceType";
  @SerializedName(SERIALIZED_NAME_INVENTORY_REFERENCE_TYPE)
  private String inventoryReferenceType;

  public static final String SERIALIZED_NAME_STATUS_CODE = "statusCode";
  @SerializedName(SERIALIZED_NAME_STATUS_CODE)
  private Integer statusCode;


  public CreateAdsByInventoryReferenceResponse adGroupId(String adGroupId) {
    
    this.adGroupId = adGroupId;
    return this;
  }

   /**
   * A unique eBay-assigned ID for an ad group in a Promoted Listings Advanced (PLA) campaign that uses the Cost Per Click (CPC) funding model.&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;b&gt;Note:&lt;/b&gt; This field will always be returned for campaigns that use the CPC funding model. It will not be returned for campaigns that use the Cost Per Sale (CPS) funding model.&lt;/span&gt;
   * @return adGroupId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A unique eBay-assigned ID for an ad group in a Promoted Listings Advanced (PLA) campaign that uses the Cost Per Click (CPC) funding model.<span class=\"tablenote\"><b>Note:</b> This field will always be returned for campaigns that use the CPC funding model. It will not be returned for campaigns that use the Cost Per Sale (CPS) funding model.</span>")

  public String getAdGroupId() {
    return adGroupId;
  }


  public void setAdGroupId(String adGroupId) {
    this.adGroupId = adGroupId;
  }


  public CreateAdsByInventoryReferenceResponse ads(List<AdReference> ads) {
    
    this.ads = ads;
    return this;
  }

  public CreateAdsByInventoryReferenceResponse addAdsItem(AdReference adsItem) {
    if (this.ads == null) {
      this.ads = new ArrayList<AdReference>();
    }
    this.ads.add(adsItem);
    return this;
  }

   /**
   * A list of ad IDs. An ad ID is generated for each successfully created ad.
   * @return ads
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "A list of ad IDs. An ad ID is generated for each successfully created ad.")

  public List<AdReference> getAds() {
    return ads;
  }


  public void setAds(List<AdReference> ads) {
    this.ads = ads;
  }


  public CreateAdsByInventoryReferenceResponse errors(List<Error> errors) {
    
    this.errors = errors;
    return this;
  }

  public CreateAdsByInventoryReferenceResponse addErrorsItem(Error errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<Error>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * An array of errors or warnings associated with the create-ads request.
   * @return errors
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "An array of errors or warnings associated with the create-ads request.")

  public List<Error> getErrors() {
    return errors;
  }


  public void setErrors(List<Error> errors) {
    this.errors = errors;
  }


  public CreateAdsByInventoryReferenceResponse inventoryReferenceId(String inventoryReferenceId) {
    
    this.inventoryReferenceId = inventoryReferenceId;
    return this;
  }

   /**
   * An ID that identifies a single-item listing or multiple-variation listing that is managed with the &lt;a href&#x3D;\&quot;/api-docs/sell/inventory/resources/methods\&quot; title&#x3D;\&quot;Inventory API Reference\&quot;&gt;Inventory API&lt;/a&gt;. &lt;p&gt;The &lt;i&gt;inventory reference ID&lt;/i&gt; is a seller-defined value that can be either an &lt;b&gt;SKU&lt;/b&gt; for a single-item listing or an &lt;b&gt;inventoryItemGroupKey&lt;/b&gt; for a multiple-value listing.&lt;/p&gt;
   * @return inventoryReferenceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An ID that identifies a single-item listing or multiple-variation listing that is managed with the <a href=\"/api-docs/sell/inventory/resources/methods\" title=\"Inventory API Reference\">Inventory API</a>. <p>The <i>inventory reference ID</i> is a seller-defined value that can be either an <b>SKU</b> for a single-item listing or an <b>inventoryItemGroupKey</b> for a multiple-value listing.</p>")

  public String getInventoryReferenceId() {
    return inventoryReferenceId;
  }


  public void setInventoryReferenceId(String inventoryReferenceId) {
    this.inventoryReferenceId = inventoryReferenceId;
  }


  public CreateAdsByInventoryReferenceResponse inventoryReferenceType(String inventoryReferenceType) {
    
    this.inventoryReferenceType = inventoryReferenceType;
    return this;
  }

   /**
   * Indicates the type of item the &lt;b&gt;inventoryReferenceId&lt;/b&gt; references. The item can be either an &lt;code&gt;INVENTORY_ITEM&lt;/code&gt; or &lt;code&gt;INVENTORY_ITEM_GROUP&lt;/code&gt;. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/marketing/types/pls:InventoryReferenceTypeEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return inventoryReferenceType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates the type of item the <b>inventoryReferenceId</b> references. The item can be either an <code>INVENTORY_ITEM</code> or <code>INVENTORY_ITEM_GROUP</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/marketing/types/pls:InventoryReferenceTypeEnum'>eBay API documentation</a>")

  public String getInventoryReferenceType() {
    return inventoryReferenceType;
  }


  public void setInventoryReferenceType(String inventoryReferenceType) {
    this.inventoryReferenceType = inventoryReferenceType;
  }


  public CreateAdsByInventoryReferenceResponse statusCode(Integer statusCode) {
    
    this.statusCode = statusCode;
    return this;
  }

   /**
   * An HTTP status code that indicates the response-status of the request. Check this code to see if the ads were successfuly created.
   * @return statusCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An HTTP status code that indicates the response-status of the request. Check this code to see if the ads were successfuly created.")

  public Integer getStatusCode() {
    return statusCode;
  }


  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateAdsByInventoryReferenceResponse createAdsByInventoryReferenceResponse = (CreateAdsByInventoryReferenceResponse) o;
    return Objects.equals(this.adGroupId, createAdsByInventoryReferenceResponse.adGroupId) &&
        Objects.equals(this.ads, createAdsByInventoryReferenceResponse.ads) &&
        Objects.equals(this.errors, createAdsByInventoryReferenceResponse.errors) &&
        Objects.equals(this.inventoryReferenceId, createAdsByInventoryReferenceResponse.inventoryReferenceId) &&
        Objects.equals(this.inventoryReferenceType, createAdsByInventoryReferenceResponse.inventoryReferenceType) &&
        Objects.equals(this.statusCode, createAdsByInventoryReferenceResponse.statusCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adGroupId, ads, errors, inventoryReferenceId, inventoryReferenceType, statusCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateAdsByInventoryReferenceResponse {\n");
    sb.append("    adGroupId: ").append(toIndentedString(adGroupId)).append("\n");
    sb.append("    ads: ").append(toIndentedString(ads)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    inventoryReferenceId: ").append(toIndentedString(inventoryReferenceId)).append("\n");
    sb.append("    inventoryReferenceType: ").append(toIndentedString(inventoryReferenceType)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

