/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.Amount;
import com.nextop.ebay.client.model.PaymentMethod;
import com.nextop.ebay.client.model.TimeDuration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * This type is used to specify/indicate that an initial deposit is required for a motor vehicle listing.
 */
@ApiModel(description = "This type is used to specify/indicate that an initial deposit is required for a motor vehicle listing.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class Deposit implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private Amount amount;

  public static final String SERIALIZED_NAME_DUE_IN = "dueIn";
  @SerializedName(SERIALIZED_NAME_DUE_IN)
  private TimeDuration dueIn;

  public static final String SERIALIZED_NAME_PAYMENT_METHODS = "paymentMethods";
  @SerializedName(SERIALIZED_NAME_PAYMENT_METHODS)
  private List<PaymentMethod> paymentMethods = null;


  public Deposit amount(Amount amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Get amount
   * @return amount
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getAmount() {
    return amount;
  }


  public void setAmount(Amount amount) {
    this.amount = amount;
  }


  public Deposit dueIn(TimeDuration dueIn) {
    
    this.dueIn = dueIn;
    return this;
  }

   /**
   * Get dueIn
   * @return dueIn
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public TimeDuration getDueIn() {
    return dueIn;
  }


  public void setDueIn(TimeDuration dueIn) {
    this.dueIn = dueIn;
  }


  public Deposit paymentMethods(List<PaymentMethod> paymentMethods) {
    
    this.paymentMethods = paymentMethods;
    return this;
  }

  public Deposit addPaymentMethodsItem(PaymentMethod paymentMethodsItem) {
    if (this.paymentMethods == null) {
      this.paymentMethods = new ArrayList<PaymentMethod>();
    }
    this.paymentMethods.add(paymentMethodsItem);
    return this;
  }

   /**
   * This array is no longer applicable and should not be used since eBay now manages the electronic payment options available to buyers to pay the deposit.
   * @return paymentMethods
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "This array is no longer applicable and should not be used since eBay now manages the electronic payment options available to buyers to pay the deposit.")

  public List<PaymentMethod> getPaymentMethods() {
    return paymentMethods;
  }


  public void setPaymentMethods(List<PaymentMethod> paymentMethods) {
    this.paymentMethods = paymentMethods;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Deposit deposit = (Deposit) o;
    return Objects.equals(this.amount, deposit.amount) &&
        Objects.equals(this.dueIn, deposit.dueIn) &&
        Objects.equals(this.paymentMethods, deposit.paymentMethods);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amount, dueIn, paymentMethods);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Deposit {\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    dueIn: ").append(toIndentedString(dueIn)).append("\n");
    sb.append("    paymentMethods: ").append(toIndentedString(paymentMethods)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

