/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.Error;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * A type that defines the response fields used by the &lt;b&gt;Keyword&lt;/b&gt; method.
 */
@ApiModel(description = "A type that defines the response fields used by the <b>Keyword</b> method.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class KeywordResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_AD_GROUP_ID = "adGroupId";
  @SerializedName(SERIALIZED_NAME_AD_GROUP_ID)
  private String adGroupId;

  public static final String SERIALIZED_NAME_ERRORS = "errors";
  @SerializedName(SERIALIZED_NAME_ERRORS)
  private List<Error> errors = null;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private String href;

  public static final String SERIALIZED_NAME_KEYWORD_ID = "keywordId";
  @SerializedName(SERIALIZED_NAME_KEYWORD_ID)
  private String keywordId;

  public static final String SERIALIZED_NAME_KEYWORD_TEXT = "keywordText";
  @SerializedName(SERIALIZED_NAME_KEYWORD_TEXT)
  private String keywordText;

  public static final String SERIALIZED_NAME_MATCH_TYPE = "matchType";
  @SerializedName(SERIALIZED_NAME_MATCH_TYPE)
  private String matchType;

  public static final String SERIALIZED_NAME_STATUS_CODE = "statusCode";
  @SerializedName(SERIALIZED_NAME_STATUS_CODE)
  private Integer statusCode;


  public KeywordResponse adGroupId(String adGroupId) {
    
    this.adGroupId = adGroupId;
    return this;
  }

   /**
   * The identifier of the ad group that the keyword was added to.
   * @return adGroupId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The identifier of the ad group that the keyword was added to.")

  public String getAdGroupId() {
    return adGroupId;
  }


  public void setAdGroupId(String adGroupId) {
    this.adGroupId = adGroupId;
  }


  public KeywordResponse errors(List<Error> errors) {
    
    this.errors = errors;
    return this;
  }

  public KeywordResponse addErrorsItem(Error errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<Error>();
    }
    this.errors.add(errorsItem);
    return this;
  }

   /**
   * This container will be returned if there is an issue creating the corresponding keyword and/or adding that keyword to the corresponding ad group.
   * @return errors
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "This container will be returned if there is an issue creating the corresponding keyword and/or adding that keyword to the corresponding ad group.")

  public List<Error> getErrors() {
    return errors;
  }


  public void setErrors(List<Error> errors) {
    this.errors = errors;
  }


  public KeywordResponse href(String href) {
    
    this.href = href;
    return this;
  }

   /**
   * The getKeyword URI for the keyword, which is used to retrieve the keyword. This URI will be returned for each successfully created keyword.
   * @return href
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The getKeyword URI for the keyword, which is used to retrieve the keyword. This URI will be returned for each successfully created keyword.")

  public String getHref() {
    return href;
  }


  public void setHref(String href) {
    this.href = href;
  }


  public KeywordResponse keywordId(String keywordId) {
    
    this.keywordId = keywordId;
    return this;
  }

   /**
   * A unique eBay-assigned ID for a keyword that is generated for an ad group. This keyword ID will be generated for each successfully created keyword.
   * @return keywordId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A unique eBay-assigned ID for a keyword that is generated for an ad group. This keyword ID will be generated for each successfully created keyword.")

  public String getKeywordId() {
    return keywordId;
  }


  public void setKeywordId(String keywordId) {
    this.keywordId = keywordId;
  }


  public KeywordResponse keywordText(String keywordText) {
    
    this.keywordText = keywordText;
    return this;
  }

   /**
   * The text of the keyword.
   * @return keywordText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The text of the keyword.")

  public String getKeywordText() {
    return keywordText;
  }


  public void setKeywordText(String keywordText) {
    this.keywordText = keywordText;
  }


  public KeywordResponse matchType(String matchType) {
    
    this.matchType = matchType;
    return this;
  }

   /**
   * A field that defines the match type for the keyword.&lt;br /&gt;&lt;br /&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;span style&#x3D;\&quot;color:#004680\&quot;&gt;&lt;strong&gt;Note:&lt;/strong&gt;&lt;/span&gt; Broad matching of keywords is currently only supported in the AU marketplace.&lt;/span&gt;&lt;br /&gt;&lt;b&gt;Valid Values:&lt;/b&gt;&lt;ul&gt;&lt;li&gt;&lt;code&gt;BROAD&lt;/code&gt;&lt;/li&gt;&lt;li&gt;&lt;code&gt;EXACT&lt;/code&gt;&lt;/li&gt;&lt;li&gt;&lt;code&gt;PHRASE&lt;/code&gt;&lt;/li&gt;&lt;/ul&gt; For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/marketing/types/pls:MatchTypeEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return matchType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A field that defines the match type for the keyword.<br /><br /><span class=\"tablenote\"><span style=\"color:#004680\"><strong>Note:</strong></span> Broad matching of keywords is currently only supported in the AU marketplace.</span><br /><b>Valid Values:</b><ul><li><code>BROAD</code></li><li><code>EXACT</code></li><li><code>PHRASE</code></li></ul> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/marketing/types/pls:MatchTypeEnum'>eBay API documentation</a>")

  public String getMatchType() {
    return matchType;
  }


  public void setMatchType(String matchType) {
    this.matchType = matchType;
  }


  public KeywordResponse statusCode(Integer statusCode) {
    
    this.statusCode = statusCode;
    return this;
  }

   /**
   * An HTTP status code is returned for each keyword to indicate the success or failure of adding that keyword to the ad group.
   * @return statusCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "An HTTP status code is returned for each keyword to indicate the success or failure of adding that keyword to the ad group.")

  public Integer getStatusCode() {
    return statusCode;
  }


  public void setStatusCode(Integer statusCode) {
    this.statusCode = statusCode;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    KeywordResponse keywordResponse = (KeywordResponse) o;
    return Objects.equals(this.adGroupId, keywordResponse.adGroupId) &&
        Objects.equals(this.errors, keywordResponse.errors) &&
        Objects.equals(this.href, keywordResponse.href) &&
        Objects.equals(this.keywordId, keywordResponse.keywordId) &&
        Objects.equals(this.keywordText, keywordResponse.keywordText) &&
        Objects.equals(this.matchType, keywordResponse.matchType) &&
        Objects.equals(this.statusCode, keywordResponse.statusCode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adGroupId, errors, href, keywordId, keywordText, matchType, statusCode);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeywordResponse {\n");
    sb.append("    adGroupId: ").append(toIndentedString(adGroupId)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    keywordId: ").append(toIndentedString(keywordId)).append("\n");
    sb.append("    keywordText: ").append(toIndentedString(keywordText)).append("\n");
    sb.append("    matchType: ").append(toIndentedString(matchType)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

