/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.Amount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * This type defines the fields in a promotion-level report.
 */
@ApiModel(description = "This type defines the fields in a promotion-level report.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class PromotionReportDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_AVERAGE_ITEM_DISCOUNT = "averageItemDiscount";
  @SerializedName(SERIALIZED_NAME_AVERAGE_ITEM_DISCOUNT)
  private Amount averageItemDiscount;

  public static final String SERIALIZED_NAME_AVERAGE_ITEM_REVENUE = "averageItemRevenue";
  @SerializedName(SERIALIZED_NAME_AVERAGE_ITEM_REVENUE)
  private Amount averageItemRevenue;

  public static final String SERIALIZED_NAME_AVERAGE_ORDER_DISCOUNT = "averageOrderDiscount";
  @SerializedName(SERIALIZED_NAME_AVERAGE_ORDER_DISCOUNT)
  private Amount averageOrderDiscount;

  public static final String SERIALIZED_NAME_AVERAGE_ORDER_REVENUE = "averageOrderRevenue";
  @SerializedName(SERIALIZED_NAME_AVERAGE_ORDER_REVENUE)
  private Amount averageOrderRevenue;

  public static final String SERIALIZED_NAME_AVERAGE_ORDER_SIZE = "averageOrderSize";
  @SerializedName(SERIALIZED_NAME_AVERAGE_ORDER_SIZE)
  private String averageOrderSize;

  public static final String SERIALIZED_NAME_BASE_SALE = "baseSale";
  @SerializedName(SERIALIZED_NAME_BASE_SALE)
  private Amount baseSale;

  public static final String SERIALIZED_NAME_ITEMS_SOLD_QUANTITY = "itemsSoldQuantity";
  @SerializedName(SERIALIZED_NAME_ITEMS_SOLD_QUANTITY)
  private Integer itemsSoldQuantity;

  public static final String SERIALIZED_NAME_NUMBER_OF_ORDERS_SOLD = "numberOfOrdersSold";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_ORDERS_SOLD)
  private Integer numberOfOrdersSold;

  public static final String SERIALIZED_NAME_PERCENTAGE_SALES_LIFT = "percentageSalesLift";
  @SerializedName(SERIALIZED_NAME_PERCENTAGE_SALES_LIFT)
  private String percentageSalesLift;

  public static final String SERIALIZED_NAME_PROMOTION_HREF = "promotionHref";
  @SerializedName(SERIALIZED_NAME_PROMOTION_HREF)
  private String promotionHref;

  public static final String SERIALIZED_NAME_PROMOTION_ID = "promotionId";
  @SerializedName(SERIALIZED_NAME_PROMOTION_ID)
  private String promotionId;

  public static final String SERIALIZED_NAME_PROMOTION_REPORT_ID = "promotionReportId";
  @SerializedName(SERIALIZED_NAME_PROMOTION_REPORT_ID)
  private String promotionReportId;

  public static final String SERIALIZED_NAME_PROMOTION_SALE = "promotionSale";
  @SerializedName(SERIALIZED_NAME_PROMOTION_SALE)
  private Amount promotionSale;

  public static final String SERIALIZED_NAME_PROMOTION_TYPE = "promotionType";
  @SerializedName(SERIALIZED_NAME_PROMOTION_TYPE)
  private String promotionType;

  public static final String SERIALIZED_NAME_TOTAL_DISCOUNT = "totalDiscount";
  @SerializedName(SERIALIZED_NAME_TOTAL_DISCOUNT)
  private Amount totalDiscount;

  public static final String SERIALIZED_NAME_TOTAL_SALE = "totalSale";
  @SerializedName(SERIALIZED_NAME_TOTAL_SALE)
  private Amount totalSale;


  public PromotionReportDetail averageItemDiscount(Amount averageItemDiscount) {
    
    this.averageItemDiscount = averageItemDiscount;
    return this;
  }

   /**
   * Get averageItemDiscount
   * @return averageItemDiscount
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getAverageItemDiscount() {
    return averageItemDiscount;
  }


  public void setAverageItemDiscount(Amount averageItemDiscount) {
    this.averageItemDiscount = averageItemDiscount;
  }


  public PromotionReportDetail averageItemRevenue(Amount averageItemRevenue) {
    
    this.averageItemRevenue = averageItemRevenue;
    return this;
  }

   /**
   * Get averageItemRevenue
   * @return averageItemRevenue
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getAverageItemRevenue() {
    return averageItemRevenue;
  }


  public void setAverageItemRevenue(Amount averageItemRevenue) {
    this.averageItemRevenue = averageItemRevenue;
  }


  public PromotionReportDetail averageOrderDiscount(Amount averageOrderDiscount) {
    
    this.averageOrderDiscount = averageOrderDiscount;
    return this;
  }

   /**
   * Get averageOrderDiscount
   * @return averageOrderDiscount
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getAverageOrderDiscount() {
    return averageOrderDiscount;
  }


  public void setAverageOrderDiscount(Amount averageOrderDiscount) {
    this.averageOrderDiscount = averageOrderDiscount;
  }


  public PromotionReportDetail averageOrderRevenue(Amount averageOrderRevenue) {
    
    this.averageOrderRevenue = averageOrderRevenue;
    return this;
  }

   /**
   * Get averageOrderRevenue
   * @return averageOrderRevenue
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getAverageOrderRevenue() {
    return averageOrderRevenue;
  }


  public void setAverageOrderRevenue(Amount averageOrderRevenue) {
    this.averageOrderRevenue = averageOrderRevenue;
  }


  public PromotionReportDetail averageOrderSize(String averageOrderSize) {
    
    this.averageOrderSize = averageOrderSize;
    return this;
  }

   /**
   * The &lt;i&gt;average order size&lt;/i&gt; is the average number of items that each order contained in a promotion. This value is calculated as follows:  &lt;br&gt;&lt;br&gt;&lt;b&gt;itemsSoldQuantity&lt;/b&gt; / &lt;b&gt;numberOfOrdersSold&lt;/b&gt; &#x3D; &lt;b&gt;averageOrderSize&lt;/b&gt; 
   * @return averageOrderSize
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The <i>average order size</i> is the average number of items that each order contained in a promotion. This value is calculated as follows:  <br><br><b>itemsSoldQuantity</b> / <b>numberOfOrdersSold</b> = <b>averageOrderSize</b> ")

  public String getAverageOrderSize() {
    return averageOrderSize;
  }


  public void setAverageOrderSize(String averageOrderSize) {
    this.averageOrderSize = averageOrderSize;
  }


  public PromotionReportDetail baseSale(Amount baseSale) {
    
    this.baseSale = baseSale;
    return this;
  }

   /**
   * Get baseSale
   * @return baseSale
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getBaseSale() {
    return baseSale;
  }


  public void setBaseSale(Amount baseSale) {
    this.baseSale = baseSale;
  }


  public PromotionReportDetail itemsSoldQuantity(Integer itemsSoldQuantity) {
    
    this.itemsSoldQuantity = itemsSoldQuantity;
    return this;
  }

   /**
   * This is the quantity of items purchased in a threshold promotion where the threshold &lt;i&gt;has been met&lt;/i&gt; and the discount was applied. &lt;br&gt;&lt;br&gt;For example, suppose you&#39;re running a \&quot;Buy 1, get 1 at 50%\&quot; promotion on $5 socks. One buyer purchases two pairs of socks, so they pay $7.50 for both pairs (rather than the full price of $10). Your number of items sold (&lt;b&gt;itemsSoldQuantity&lt;/b&gt;) would be 2 and you number of orders sold (&lt;b&gt;numberOfOrdersSold&lt;/b&gt;) would be 1.
   * @return itemsSoldQuantity
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This is the quantity of items purchased in a threshold promotion where the threshold <i>has been met</i> and the discount was applied. <br><br>For example, suppose you're running a \"Buy 1, get 1 at 50%\" promotion on $5 socks. One buyer purchases two pairs of socks, so they pay $7.50 for both pairs (rather than the full price of $10). Your number of items sold (<b>itemsSoldQuantity</b>) would be 2 and you number of orders sold (<b>numberOfOrdersSold</b>) would be 1.")

  public Integer getItemsSoldQuantity() {
    return itemsSoldQuantity;
  }


  public void setItemsSoldQuantity(Integer itemsSoldQuantity) {
    this.itemsSoldQuantity = itemsSoldQuantity;
  }


  public PromotionReportDetail numberOfOrdersSold(Integer numberOfOrdersSold) {
    
    this.numberOfOrdersSold = numberOfOrdersSold;
    return this;
  }

   /**
   * This is the number of orders sold in a threshold promotion where the threshold &lt;i&gt;has been met&lt;/i&gt; and the discount was applied. &lt;br&gt;&lt;br&gt;For example, suppose you&#39;re running a \&quot;Buy 1, get 1 at 50%\&quot; promotion on $5 socks. One buyer purchases two pairs of socks, so they pay $7.50 for both pairs (rather than the full price of $10). Your &lt;b&gt;numberOfOrdersSold&lt;/b&gt; would be 1 and your &lt;b&gt;itemsSoldQuantity&lt;/b&gt; would be 2.
   * @return numberOfOrdersSold
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This is the number of orders sold in a threshold promotion where the threshold <i>has been met</i> and the discount was applied. <br><br>For example, suppose you're running a \"Buy 1, get 1 at 50%\" promotion on $5 socks. One buyer purchases two pairs of socks, so they pay $7.50 for both pairs (rather than the full price of $10). Your <b>numberOfOrdersSold</b> would be 1 and your <b>itemsSoldQuantity</b> would be 2.")

  public Integer getNumberOfOrdersSold() {
    return numberOfOrdersSold;
  }


  public void setNumberOfOrdersSold(Integer numberOfOrdersSold) {
    this.numberOfOrdersSold = numberOfOrdersSold;
  }


  public PromotionReportDetail percentageSalesLift(String percentageSalesLift) {
    
    this.percentageSalesLift = percentageSalesLift;
    return this;
  }

   /**
   * The &lt;i&gt;percentage sales lift&lt;/i&gt; is the total dollar amount gained due to promotions. This value is calculated as follows:  &lt;br&gt;&lt;br&gt; &lt;b&gt;promotionSale&lt;/b&gt; / &lt;b&gt;totalSale&lt;/b&gt; &#x3D;  &lt;b&gt;percentageSalesLift&lt;/b&gt; 
   * @return percentageSalesLift
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The <i>percentage sales lift</i> is the total dollar amount gained due to promotions. This value is calculated as follows:  <br><br> <b>promotionSale</b> / <b>totalSale</b> =  <b>percentageSalesLift</b> ")

  public String getPercentageSalesLift() {
    return percentageSalesLift;
  }


  public void setPercentageSalesLift(String percentageSalesLift) {
    this.percentageSalesLift = percentageSalesLift;
  }


  public PromotionReportDetail promotionHref(String promotionHref) {
    
    this.promotionHref = promotionHref;
    return this;
  }

   /**
   * The URI of the promotion report.
   * @return promotionHref
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The URI of the promotion report.")

  public String getPromotionHref() {
    return promotionHref;
  }


  public void setPromotionHref(String promotionHref) {
    this.promotionHref = promotionHref;
  }


  public PromotionReportDetail promotionId(String promotionId) {
    
    this.promotionId = promotionId;
    return this;
  }

   /**
   * A unique eBay-assigned ID for the promotion that&#39;s generated when the promotion is created.
   * @return promotionId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A unique eBay-assigned ID for the promotion that's generated when the promotion is created.")

  public String getPromotionId() {
    return promotionId;
  }


  public void setPromotionId(String promotionId) {
    this.promotionId = promotionId;
  }


  public PromotionReportDetail promotionReportId(String promotionReportId) {
    
    this.promotionReportId = promotionReportId;
    return this;
  }

   /**
   * The unique eBay-assigned ID of the promotion report that is generated when the report is created.
   * @return promotionReportId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique eBay-assigned ID of the promotion report that is generated when the report is created.")

  public String getPromotionReportId() {
    return promotionReportId;
  }


  public void setPromotionReportId(String promotionReportId) {
    this.promotionReportId = promotionReportId;
  }


  public PromotionReportDetail promotionSale(Amount promotionSale) {
    
    this.promotionSale = promotionSale;
    return this;
  }

   /**
   * Get promotionSale
   * @return promotionSale
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getPromotionSale() {
    return promotionSale;
  }


  public void setPromotionSale(Amount promotionSale) {
    this.promotionSale = promotionSale;
  }


  public PromotionReportDetail promotionType(String promotionType) {
    
    this.promotionType = promotionType;
    return this;
  }

   /**
   * Indicates the type of the promotion, either &lt;code&gt;CODED_COUPON&lt;/code&gt;, &lt;code&gt;MARKDOWN_SALE&lt;/code&gt;, &lt;code&gt;ORDER_DISCOUNT&lt;/code&gt;, or &lt;code&gt;VOLUME_DISCOUNT&lt;/code&gt;. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/marketing/types/sme:PromotionTypeEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return promotionType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Indicates the type of the promotion, either <code>CODED_COUPON</code>, <code>MARKDOWN_SALE</code>, <code>ORDER_DISCOUNT</code>, or <code>VOLUME_DISCOUNT</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/marketing/types/sme:PromotionTypeEnum'>eBay API documentation</a>")

  public String getPromotionType() {
    return promotionType;
  }


  public void setPromotionType(String promotionType) {
    this.promotionType = promotionType;
  }


  public PromotionReportDetail totalDiscount(Amount totalDiscount) {
    
    this.totalDiscount = totalDiscount;
    return this;
  }

   /**
   * Get totalDiscount
   * @return totalDiscount
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getTotalDiscount() {
    return totalDiscount;
  }


  public void setTotalDiscount(Amount totalDiscount) {
    this.totalDiscount = totalDiscount;
  }


  public PromotionReportDetail totalSale(Amount totalSale) {
    
    this.totalSale = totalSale;
    return this;
  }

   /**
   * Get totalSale
   * @return totalSale
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getTotalSale() {
    return totalSale;
  }


  public void setTotalSale(Amount totalSale) {
    this.totalSale = totalSale;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PromotionReportDetail promotionReportDetail = (PromotionReportDetail) o;
    return Objects.equals(this.averageItemDiscount, promotionReportDetail.averageItemDiscount) &&
        Objects.equals(this.averageItemRevenue, promotionReportDetail.averageItemRevenue) &&
        Objects.equals(this.averageOrderDiscount, promotionReportDetail.averageOrderDiscount) &&
        Objects.equals(this.averageOrderRevenue, promotionReportDetail.averageOrderRevenue) &&
        Objects.equals(this.averageOrderSize, promotionReportDetail.averageOrderSize) &&
        Objects.equals(this.baseSale, promotionReportDetail.baseSale) &&
        Objects.equals(this.itemsSoldQuantity, promotionReportDetail.itemsSoldQuantity) &&
        Objects.equals(this.numberOfOrdersSold, promotionReportDetail.numberOfOrdersSold) &&
        Objects.equals(this.percentageSalesLift, promotionReportDetail.percentageSalesLift) &&
        Objects.equals(this.promotionHref, promotionReportDetail.promotionHref) &&
        Objects.equals(this.promotionId, promotionReportDetail.promotionId) &&
        Objects.equals(this.promotionReportId, promotionReportDetail.promotionReportId) &&
        Objects.equals(this.promotionSale, promotionReportDetail.promotionSale) &&
        Objects.equals(this.promotionType, promotionReportDetail.promotionType) &&
        Objects.equals(this.totalDiscount, promotionReportDetail.totalDiscount) &&
        Objects.equals(this.totalSale, promotionReportDetail.totalSale);
  }

  @Override
  public int hashCode() {
    return Objects.hash(averageItemDiscount, averageItemRevenue, averageOrderDiscount, averageOrderRevenue, averageOrderSize, baseSale, itemsSoldQuantity, numberOfOrdersSold, percentageSalesLift, promotionHref, promotionId, promotionReportId, promotionSale, promotionType, totalDiscount, totalSale);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PromotionReportDetail {\n");
    sb.append("    averageItemDiscount: ").append(toIndentedString(averageItemDiscount)).append("\n");
    sb.append("    averageItemRevenue: ").append(toIndentedString(averageItemRevenue)).append("\n");
    sb.append("    averageOrderDiscount: ").append(toIndentedString(averageOrderDiscount)).append("\n");
    sb.append("    averageOrderRevenue: ").append(toIndentedString(averageOrderRevenue)).append("\n");
    sb.append("    averageOrderSize: ").append(toIndentedString(averageOrderSize)).append("\n");
    sb.append("    baseSale: ").append(toIndentedString(baseSale)).append("\n");
    sb.append("    itemsSoldQuantity: ").append(toIndentedString(itemsSoldQuantity)).append("\n");
    sb.append("    numberOfOrdersSold: ").append(toIndentedString(numberOfOrdersSold)).append("\n");
    sb.append("    percentageSalesLift: ").append(toIndentedString(percentageSalesLift)).append("\n");
    sb.append("    promotionHref: ").append(toIndentedString(promotionHref)).append("\n");
    sb.append("    promotionId: ").append(toIndentedString(promotionId)).append("\n");
    sb.append("    promotionReportId: ").append(toIndentedString(promotionReportId)).append("\n");
    sb.append("    promotionSale: ").append(toIndentedString(promotionSale)).append("\n");
    sb.append("    promotionType: ").append(toIndentedString(promotionType)).append("\n");
    sb.append("    totalDiscount: ").append(toIndentedString(totalDiscount)).append("\n");
    sb.append("    totalSale: ").append(toIndentedString(totalSale)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

