/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.AdditionalOption;
import com.nextop.ebay.client.model.Amount;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * The \&quot;rate\&quot; that has been selected and purchased for the shipment, as referenced by the &lt;b&gt;rateId&lt;/b&gt; value.
 */
@ApiModel(description = "The \"rate\" that has been selected and purchased for the shipment, as referenced by the <b>rateId</b> value.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class PurchasedRate implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_ADDITIONAL_OPTIONS = "additionalOptions";
  @SerializedName(SERIALIZED_NAME_ADDITIONAL_OPTIONS)
  private List<AdditionalOption> additionalOptions = null;

  public static final String SERIALIZED_NAME_BASE_SHIPPING_COST = "baseShippingCost";
  @SerializedName(SERIALIZED_NAME_BASE_SHIPPING_COST)
  private Amount baseShippingCost;

  public static final String SERIALIZED_NAME_DESTINATION_TIME_ZONE = "destinationTimeZone";
  @SerializedName(SERIALIZED_NAME_DESTINATION_TIME_ZONE)
  private String destinationTimeZone;

  public static final String SERIALIZED_NAME_MAX_ESTIMATED_DELIVERY_DATE = "maxEstimatedDeliveryDate";
  @SerializedName(SERIALIZED_NAME_MAX_ESTIMATED_DELIVERY_DATE)
  private String maxEstimatedDeliveryDate;

  public static final String SERIALIZED_NAME_MIN_ESTIMATED_DELIVERY_DATE = "minEstimatedDeliveryDate";
  @SerializedName(SERIALIZED_NAME_MIN_ESTIMATED_DELIVERY_DATE)
  private String minEstimatedDeliveryDate;

  public static final String SERIALIZED_NAME_PICKUP_NETWORKS = "pickupNetworks";
  @SerializedName(SERIALIZED_NAME_PICKUP_NETWORKS)
  private List<String> pickupNetworks = null;

  public static final String SERIALIZED_NAME_PICKUP_SLOT_ID = "pickupSlotId";
  @SerializedName(SERIALIZED_NAME_PICKUP_SLOT_ID)
  private String pickupSlotId;

  public static final String SERIALIZED_NAME_PICKUP_TYPE = "pickupType";
  @SerializedName(SERIALIZED_NAME_PICKUP_TYPE)
  private String pickupType;

  public static final String SERIALIZED_NAME_RATE_ID = "rateId";
  @SerializedName(SERIALIZED_NAME_RATE_ID)
  private String rateId;

  public static final String SERIALIZED_NAME_SHIPPING_CARRIER_CODE = "shippingCarrierCode";
  @SerializedName(SERIALIZED_NAME_SHIPPING_CARRIER_CODE)
  private String shippingCarrierCode;

  public static final String SERIALIZED_NAME_SHIPPING_CARRIER_NAME = "shippingCarrierName";
  @SerializedName(SERIALIZED_NAME_SHIPPING_CARRIER_NAME)
  private String shippingCarrierName;

  public static final String SERIALIZED_NAME_SHIPPING_QUOTE_ID = "shippingQuoteId";
  @SerializedName(SERIALIZED_NAME_SHIPPING_QUOTE_ID)
  private String shippingQuoteId;

  public static final String SERIALIZED_NAME_SHIPPING_SERVICE_CODE = "shippingServiceCode";
  @SerializedName(SERIALIZED_NAME_SHIPPING_SERVICE_CODE)
  private String shippingServiceCode;

  public static final String SERIALIZED_NAME_SHIPPING_SERVICE_NAME = "shippingServiceName";
  @SerializedName(SERIALIZED_NAME_SHIPPING_SERVICE_NAME)
  private String shippingServiceName;

  public static final String SERIALIZED_NAME_TOTAL_SHIPPING_COST = "totalShippingCost";
  @SerializedName(SERIALIZED_NAME_TOTAL_SHIPPING_COST)
  private Amount totalShippingCost;


  public PurchasedRate additionalOptions(List<AdditionalOption> additionalOptions) {
    
    this.additionalOptions = additionalOptions;
    return this;
  }

  public PurchasedRate addAdditionalOptionsItem(AdditionalOption additionalOptionsItem) {
    if (this.additionalOptions == null) {
      this.additionalOptions = new ArrayList<AdditionalOption>();
    }
    this.additionalOptions.add(additionalOptionsItem);
    return this;
  }

   /**
   * An list of additional, optional features that have been purchased for the shipment.
   * @return additionalOptions
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "An list of additional, optional features that have been purchased for the shipment.")

  public List<AdditionalOption> getAdditionalOptions() {
    return additionalOptions;
  }


  public void setAdditionalOptions(List<AdditionalOption> additionalOptions) {
    this.additionalOptions = additionalOptions;
  }


  public PurchasedRate baseShippingCost(Amount baseShippingCost) {
    
    this.baseShippingCost = baseShippingCost;
    return this;
  }

   /**
   * Get baseShippingCost
   * @return baseShippingCost
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getBaseShippingCost() {
    return baseShippingCost;
  }


  public void setBaseShippingCost(Amount baseShippingCost) {
    this.baseShippingCost = baseShippingCost;
  }


  public PurchasedRate destinationTimeZone(String destinationTimeZone) {
    
    this.destinationTimeZone = destinationTimeZone;
    return this;
  }

   /**
   * The time zone of the destination according to &lt;a href&#x3D;\&quot;https://www.iana.org/time-zones\&quot; target&#x3D;\&quot;_blank\&quot;&gt;Time Zone Database&lt;/a&gt;. For example, \&quot;America/Los_Angeles\&quot;.
   * @return destinationTimeZone
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The time zone of the destination according to <a href=\"https://www.iana.org/time-zones\" target=\"_blank\">Time Zone Database</a>. For example, \"America/Los_Angeles\".")

  public String getDestinationTimeZone() {
    return destinationTimeZone;
  }


  public void setDestinationTimeZone(String destinationTimeZone) {
    this.destinationTimeZone = destinationTimeZone;
  }


  public PurchasedRate maxEstimatedDeliveryDate(String maxEstimatedDeliveryDate) {
    
    this.maxEstimatedDeliveryDate = maxEstimatedDeliveryDate;
    return this;
  }

   /**
   * A string value representing maximum (latest) estimated delivery time, formatted as an &lt;a href&#x3D;\&quot;https://www.iso.org/iso-8601-date-and-time-format.html\&quot; title&#x3D;\&quot;https://www.iso.org\&quot; target&#x3D;\&quot;_blank\&quot;&gt;ISO 8601&lt;/a&gt; string, which is based on the 24-hour Coordinated Universal Time (UTC) clock.  &lt;br&gt;&lt;br&gt;&lt;b&gt;Format:&lt;/b&gt; &lt;code&gt;[YYYY]-[MM]-[DD]T[HH]:[MM]:[SS].[SSS]Z&lt;/code&gt; &lt;br&gt;&lt;b&gt;Example:&lt;/b&gt; &lt;code&gt;2018-08-20T07:09:00.000Z&lt;/code&gt;
   * @return maxEstimatedDeliveryDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A string value representing maximum (latest) estimated delivery time, formatted as an <a href=\"https://www.iso.org/iso-8601-date-and-time-format.html\" title=\"https://www.iso.org\" target=\"_blank\">ISO 8601</a> string, which is based on the 24-hour Coordinated Universal Time (UTC) clock.  <br><br><b>Format:</b> <code>[YYYY]-[MM]-[DD]T[HH]:[MM]:[SS].[SSS]Z</code> <br><b>Example:</b> <code>2018-08-20T07:09:00.000Z</code>")

  public String getMaxEstimatedDeliveryDate() {
    return maxEstimatedDeliveryDate;
  }


  public void setMaxEstimatedDeliveryDate(String maxEstimatedDeliveryDate) {
    this.maxEstimatedDeliveryDate = maxEstimatedDeliveryDate;
  }


  public PurchasedRate minEstimatedDeliveryDate(String minEstimatedDeliveryDate) {
    
    this.minEstimatedDeliveryDate = minEstimatedDeliveryDate;
    return this;
  }

   /**
   * A string value representing minimum (earliest) estimated delivery time, formatted as an &lt;a href&#x3D;\&quot;https://www.iso.org/iso-8601-date-and-time-format.html\&quot; title&#x3D;\&quot;https://www.iso.org\&quot; target&#x3D;\&quot;_blank\&quot;&gt;ISO 8601&lt;/a&gt;ISO 8601&lt;/a&gt; UTC string.
   * @return minEstimatedDeliveryDate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A string value representing minimum (earliest) estimated delivery time, formatted as an <a href=\"https://www.iso.org/iso-8601-date-and-time-format.html\" title=\"https://www.iso.org\" target=\"_blank\">ISO 8601</a>ISO 8601</a> UTC string.")

  public String getMinEstimatedDeliveryDate() {
    return minEstimatedDeliveryDate;
  }


  public void setMinEstimatedDeliveryDate(String minEstimatedDeliveryDate) {
    this.minEstimatedDeliveryDate = minEstimatedDeliveryDate;
  }


  public PurchasedRate pickupNetworks(List<String> pickupNetworks) {
    
    this.pickupNetworks = pickupNetworks;
    return this;
  }

  public PurchasedRate addPickupNetworksItem(String pickupNetworksItem) {
    if (this.pickupNetworks == null) {
      this.pickupNetworks = new ArrayList<String>();
    }
    this.pickupNetworks.add(pickupNetworksItem);
    return this;
  }

   /**
   * A list of pickup networks compatible with the shipping service.
   * @return pickupNetworks
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A list of pickup networks compatible with the shipping service.")

  public List<String> getPickupNetworks() {
    return pickupNetworks;
  }


  public void setPickupNetworks(List<String> pickupNetworks) {
    this.pickupNetworks = pickupNetworks;
  }


  public PurchasedRate pickupSlotId(String pickupSlotId) {
    
    this.pickupSlotId = pickupSlotId;
    return this;
  }

   /**
   * This unique eBay-assigned ID value is returned only if the shipment has been configured for a scheduled pickup.
   * @return pickupSlotId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This unique eBay-assigned ID value is returned only if the shipment has been configured for a scheduled pickup.")

  public String getPickupSlotId() {
    return pickupSlotId;
  }


  public void setPickupSlotId(String pickupSlotId) {
    this.pickupSlotId = pickupSlotId;
  }


  public PurchasedRate pickupType(String pickupType) {
    
    this.pickupType = pickupType;
    return this;
  }

   /**
   * The type of pickup or drop off configured for the shipment. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/logistics/types/api:PickupTypeEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return pickupType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The type of pickup or drop off configured for the shipment. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/logistics/types/api:PickupTypeEnum'>eBay API documentation</a>")

  public String getPickupType() {
    return pickupType;
  }


  public void setPickupType(String pickupType) {
    this.pickupType = pickupType;
  }


  public PurchasedRate rateId(String rateId) {
    
    this.rateId = rateId;
    return this;
  }

   /**
   * The eBay-generated ID of the shipping rate that the seller has chosen to purchase for the shipment.
   * @return rateId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The eBay-generated ID of the shipping rate that the seller has chosen to purchase for the shipment.")

  public String getRateId() {
    return rateId;
  }


  public void setRateId(String rateId) {
    this.rateId = rateId;
  }


  public PurchasedRate shippingCarrierCode(String shippingCarrierCode) {
    
    this.shippingCarrierCode = shippingCarrierCode;
    return this;
  }

   /**
   * The ID code for the carrier that was selected for the package shipment.
   * @return shippingCarrierCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID code for the carrier that was selected for the package shipment.")

  public String getShippingCarrierCode() {
    return shippingCarrierCode;
  }


  public void setShippingCarrierCode(String shippingCarrierCode) {
    this.shippingCarrierCode = shippingCarrierCode;
  }


  public PurchasedRate shippingCarrierName(String shippingCarrierName) {
    
    this.shippingCarrierName = shippingCarrierName;
    return this;
  }

   /**
   * The name of the shipping carrier.
   * @return shippingCarrierName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the shipping carrier.")

  public String getShippingCarrierName() {
    return shippingCarrierName;
  }


  public void setShippingCarrierName(String shippingCarrierName) {
    this.shippingCarrierName = shippingCarrierName;
  }


  public PurchasedRate shippingQuoteId(String shippingQuoteId) {
    
    this.shippingQuoteId = shippingQuoteId;
    return this;
  }

   /**
   * The unique eBay-generated ID of the &lt;i&gt;shipping quote&lt;/i&gt; from which the seller selected a shipping rate (&lt;b&gt;rateId&lt;/b&gt;).
   * @return shippingQuoteId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The unique eBay-generated ID of the <i>shipping quote</i> from which the seller selected a shipping rate (<b>rateId</b>).")

  public String getShippingQuoteId() {
    return shippingQuoteId;
  }


  public void setShippingQuoteId(String shippingQuoteId) {
    this.shippingQuoteId = shippingQuoteId;
  }


  public PurchasedRate shippingServiceCode(String shippingServiceCode) {
    
    this.shippingServiceCode = shippingServiceCode;
    return this;
  }

   /**
   * String ID code for the shipping service selected for the package shipment. This is a service that the shipping carrier supplies.
   * @return shippingServiceCode
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "String ID code for the shipping service selected for the package shipment. This is a service that the shipping carrier supplies.")

  public String getShippingServiceCode() {
    return shippingServiceCode;
  }


  public void setShippingServiceCode(String shippingServiceCode) {
    this.shippingServiceCode = shippingServiceCode;
  }


  public PurchasedRate shippingServiceName(String shippingServiceName) {
    
    this.shippingServiceName = shippingServiceName;
    return this;
  }

   /**
   * The name of the shipping service.
   * @return shippingServiceName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The name of the shipping service.")

  public String getShippingServiceName() {
    return shippingServiceName;
  }


  public void setShippingServiceName(String shippingServiceName) {
    this.shippingServiceName = shippingServiceName;
  }


  public PurchasedRate totalShippingCost(Amount totalShippingCost) {
    
    this.totalShippingCost = totalShippingCost;
    return this;
  }

   /**
   * Get totalShippingCost
   * @return totalShippingCost
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public Amount getTotalShippingCost() {
    return totalShippingCost;
  }


  public void setTotalShippingCost(Amount totalShippingCost) {
    this.totalShippingCost = totalShippingCost;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PurchasedRate purchasedRate = (PurchasedRate) o;
    return Objects.equals(this.additionalOptions, purchasedRate.additionalOptions) &&
        Objects.equals(this.baseShippingCost, purchasedRate.baseShippingCost) &&
        Objects.equals(this.destinationTimeZone, purchasedRate.destinationTimeZone) &&
        Objects.equals(this.maxEstimatedDeliveryDate, purchasedRate.maxEstimatedDeliveryDate) &&
        Objects.equals(this.minEstimatedDeliveryDate, purchasedRate.minEstimatedDeliveryDate) &&
        Objects.equals(this.pickupNetworks, purchasedRate.pickupNetworks) &&
        Objects.equals(this.pickupSlotId, purchasedRate.pickupSlotId) &&
        Objects.equals(this.pickupType, purchasedRate.pickupType) &&
        Objects.equals(this.rateId, purchasedRate.rateId) &&
        Objects.equals(this.shippingCarrierCode, purchasedRate.shippingCarrierCode) &&
        Objects.equals(this.shippingCarrierName, purchasedRate.shippingCarrierName) &&
        Objects.equals(this.shippingQuoteId, purchasedRate.shippingQuoteId) &&
        Objects.equals(this.shippingServiceCode, purchasedRate.shippingServiceCode) &&
        Objects.equals(this.shippingServiceName, purchasedRate.shippingServiceName) &&
        Objects.equals(this.totalShippingCost, purchasedRate.totalShippingCost);
  }

  @Override
  public int hashCode() {
    return Objects.hash(additionalOptions, baseShippingCost, destinationTimeZone, maxEstimatedDeliveryDate, minEstimatedDeliveryDate, pickupNetworks, pickupSlotId, pickupType, rateId, shippingCarrierCode, shippingCarrierName, shippingQuoteId, shippingServiceCode, shippingServiceName, totalShippingCost);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PurchasedRate {\n");
    sb.append("    additionalOptions: ").append(toIndentedString(additionalOptions)).append("\n");
    sb.append("    baseShippingCost: ").append(toIndentedString(baseShippingCost)).append("\n");
    sb.append("    destinationTimeZone: ").append(toIndentedString(destinationTimeZone)).append("\n");
    sb.append("    maxEstimatedDeliveryDate: ").append(toIndentedString(maxEstimatedDeliveryDate)).append("\n");
    sb.append("    minEstimatedDeliveryDate: ").append(toIndentedString(minEstimatedDeliveryDate)).append("\n");
    sb.append("    pickupNetworks: ").append(toIndentedString(pickupNetworks)).append("\n");
    sb.append("    pickupSlotId: ").append(toIndentedString(pickupSlotId)).append("\n");
    sb.append("    pickupType: ").append(toIndentedString(pickupType)).append("\n");
    sb.append("    rateId: ").append(toIndentedString(rateId)).append("\n");
    sb.append("    shippingCarrierCode: ").append(toIndentedString(shippingCarrierCode)).append("\n");
    sb.append("    shippingCarrierName: ").append(toIndentedString(shippingCarrierName)).append("\n");
    sb.append("    shippingQuoteId: ").append(toIndentedString(shippingQuoteId)).append("\n");
    sb.append("    shippingServiceCode: ").append(toIndentedString(shippingServiceCode)).append("\n");
    sb.append("    shippingServiceName: ").append(toIndentedString(shippingServiceName)).append("\n");
    sb.append("    totalShippingCost: ").append(toIndentedString(totalShippingCost)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

