/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.DimensionMetadata;
import com.nextop.ebay.client.model.MetricMetadata;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * This type defines the fields included in the report.
 */
@ApiModel(description = "This type defines the fields included in the report.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class ReportMetadata implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_DIMENSION_METADATA = "dimensionMetadata";
  @SerializedName(SERIALIZED_NAME_DIMENSION_METADATA)
  private List<DimensionMetadata> dimensionMetadata = null;

  public static final String SERIALIZED_NAME_MAX_NUMBER_OF_DIMENSIONS_TO_REQUEST = "maxNumberOfDimensionsToRequest";
  @SerializedName(SERIALIZED_NAME_MAX_NUMBER_OF_DIMENSIONS_TO_REQUEST)
  private Integer maxNumberOfDimensionsToRequest;

  public static final String SERIALIZED_NAME_MAX_NUMBER_OF_METRICS_TO_REQUEST = "maxNumberOfMetricsToRequest";
  @SerializedName(SERIALIZED_NAME_MAX_NUMBER_OF_METRICS_TO_REQUEST)
  private Integer maxNumberOfMetricsToRequest;

  public static final String SERIALIZED_NAME_METRIC_METADATA = "metricMetadata";
  @SerializedName(SERIALIZED_NAME_METRIC_METADATA)
  private List<MetricMetadata> metricMetadata = null;

  public static final String SERIALIZED_NAME_REPORT_TYPE = "reportType";
  @SerializedName(SERIALIZED_NAME_REPORT_TYPE)
  private String reportType;


  public ReportMetadata dimensionMetadata(List<DimensionMetadata> dimensionMetadata) {
    
    this.dimensionMetadata = dimensionMetadata;
    return this;
  }

  public ReportMetadata addDimensionMetadataItem(DimensionMetadata dimensionMetadataItem) {
    if (this.dimensionMetadata == null) {
      this.dimensionMetadata = new ArrayList<DimensionMetadata>();
    }
    this.dimensionMetadata.add(dimensionMetadataItem);
    return this;
  }

   /**
   * A list containing the metadata for the dimension used in the report.
   * @return dimensionMetadata
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "A list containing the metadata for the dimension used in the report.")

  public List<DimensionMetadata> getDimensionMetadata() {
    return dimensionMetadata;
  }


  public void setDimensionMetadata(List<DimensionMetadata> dimensionMetadata) {
    this.dimensionMetadata = dimensionMetadata;
  }


  public ReportMetadata maxNumberOfDimensionsToRequest(Integer maxNumberOfDimensionsToRequest) {
    
    this.maxNumberOfDimensionsToRequest = maxNumberOfDimensionsToRequest;
    return this;
  }

   /**
   * The maximum number of dimensions that can be requested for the specified report type.
   * @return maxNumberOfDimensionsToRequest
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The maximum number of dimensions that can be requested for the specified report type.")

  public Integer getMaxNumberOfDimensionsToRequest() {
    return maxNumberOfDimensionsToRequest;
  }


  public void setMaxNumberOfDimensionsToRequest(Integer maxNumberOfDimensionsToRequest) {
    this.maxNumberOfDimensionsToRequest = maxNumberOfDimensionsToRequest;
  }


  public ReportMetadata maxNumberOfMetricsToRequest(Integer maxNumberOfMetricsToRequest) {
    
    this.maxNumberOfMetricsToRequest = maxNumberOfMetricsToRequest;
    return this;
  }

   /**
   * The maximum number of metrics that can be requested for the specified report type.
   * @return maxNumberOfMetricsToRequest
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The maximum number of metrics that can be requested for the specified report type.")

  public Integer getMaxNumberOfMetricsToRequest() {
    return maxNumberOfMetricsToRequest;
  }


  public void setMaxNumberOfMetricsToRequest(Integer maxNumberOfMetricsToRequest) {
    this.maxNumberOfMetricsToRequest = maxNumberOfMetricsToRequest;
  }


  public ReportMetadata metricMetadata(List<MetricMetadata> metricMetadata) {
    
    this.metricMetadata = metricMetadata;
    return this;
  }

  public ReportMetadata addMetricMetadataItem(MetricMetadata metricMetadataItem) {
    if (this.metricMetadata == null) {
      this.metricMetadata = new ArrayList<MetricMetadata>();
    }
    this.metricMetadata.add(metricMetadataItem);
    return this;
  }

   /**
   * A list containing the metadata for the metrics in the report.
   * @return metricMetadata
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "A list containing the metadata for the metrics in the report.")

  public List<MetricMetadata> getMetricMetadata() {
    return metricMetadata;
  }


  public void setMetricMetadata(List<MetricMetadata> metricMetadata) {
    this.metricMetadata = metricMetadata;
  }


  public ReportMetadata reportType(String reportType) {
    
    this.reportType = reportType;
    return this;
  }

   /**
   * The &lt;b&gt;report_type&lt;/b&gt;, as specified in the request to create the report task.&lt;br/&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;b&gt;Note:&lt;/b&gt; INVENTORY_PERFORMANCE_REPORT is not currently available; availability date is pending.&lt;/span&gt; For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/marketing/types/plr:ReportTypeEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return reportType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The <b>report_type</b>, as specified in the request to create the report task.<br/><br/><span class=\"tablenote\"><b>Note:</b> INVENTORY_PERFORMANCE_REPORT is not currently available; availability date is pending.</span> For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/marketing/types/plr:ReportTypeEnum'>eBay API documentation</a>")

  public String getReportType() {
    return reportType;
  }


  public void setReportType(String reportType) {
    this.reportType = reportType;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReportMetadata reportMetadata = (ReportMetadata) o;
    return Objects.equals(this.dimensionMetadata, reportMetadata.dimensionMetadata) &&
        Objects.equals(this.maxNumberOfDimensionsToRequest, reportMetadata.maxNumberOfDimensionsToRequest) &&
        Objects.equals(this.maxNumberOfMetricsToRequest, reportMetadata.maxNumberOfMetricsToRequest) &&
        Objects.equals(this.metricMetadata, reportMetadata.metricMetadata) &&
        Objects.equals(this.reportType, reportMetadata.reportType);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dimensionMetadata, maxNumberOfDimensionsToRequest, maxNumberOfMetricsToRequest, metricMetadata, reportType);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReportMetadata {\n");
    sb.append("    dimensionMetadata: ").append(toIndentedString(dimensionMetadata)).append("\n");
    sb.append("    maxNumberOfDimensionsToRequest: ").append(toIndentedString(maxNumberOfDimensionsToRequest)).append("\n");
    sb.append("    maxNumberOfMetricsToRequest: ").append(toIndentedString(maxNumberOfMetricsToRequest)).append("\n");
    sb.append("    metricMetadata: ").append(toIndentedString(metricMetadata)).append("\n");
    sb.append("    reportType: ").append(toIndentedString(reportType)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

