/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.CategoryType;
import com.nextop.ebay.client.model.InternationalReturnOverrideType;
import com.nextop.ebay.client.model.TimeDuration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * This type is used by the &lt;b&gt;returnPolicy&lt;/b&gt; response container, a container which defines a seller&#39;s return business policy for a specific marketplace.
 */
@ApiModel(description = "This type is used by the <b>returnPolicy</b> response container, a container which defines a seller's return business policy for a specific marketplace.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class ReturnPolicy implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CATEGORY_TYPES = "categoryTypes";
  @SerializedName(SERIALIZED_NAME_CATEGORY_TYPES)
  private List<CategoryType> categoryTypes = null;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_EXTENDED_HOLIDAY_RETURNS_OFFERED = "extendedHolidayReturnsOffered";
  @SerializedName(SERIALIZED_NAME_EXTENDED_HOLIDAY_RETURNS_OFFERED)
  private Boolean extendedHolidayReturnsOffered;

  public static final String SERIALIZED_NAME_INTERNATIONAL_OVERRIDE = "internationalOverride";
  @SerializedName(SERIALIZED_NAME_INTERNATIONAL_OVERRIDE)
  private InternationalReturnOverrideType internationalOverride;

  public static final String SERIALIZED_NAME_MARKETPLACE_ID = "marketplaceId";
  @SerializedName(SERIALIZED_NAME_MARKETPLACE_ID)
  private String marketplaceId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_REFUND_METHOD = "refundMethod";
  @SerializedName(SERIALIZED_NAME_REFUND_METHOD)
  private String refundMethod;

  public static final String SERIALIZED_NAME_RESTOCKING_FEE_PERCENTAGE = "restockingFeePercentage";
  @SerializedName(SERIALIZED_NAME_RESTOCKING_FEE_PERCENTAGE)
  private String restockingFeePercentage;

  public static final String SERIALIZED_NAME_RETURN_INSTRUCTIONS = "returnInstructions";
  @SerializedName(SERIALIZED_NAME_RETURN_INSTRUCTIONS)
  private String returnInstructions;

  public static final String SERIALIZED_NAME_RETURN_METHOD = "returnMethod";
  @SerializedName(SERIALIZED_NAME_RETURN_METHOD)
  private String returnMethod;

  public static final String SERIALIZED_NAME_RETURN_PERIOD = "returnPeriod";
  @SerializedName(SERIALIZED_NAME_RETURN_PERIOD)
  private TimeDuration returnPeriod;

  public static final String SERIALIZED_NAME_RETURN_POLICY_ID = "returnPolicyId";
  @SerializedName(SERIALIZED_NAME_RETURN_POLICY_ID)
  private String returnPolicyId;

  public static final String SERIALIZED_NAME_RETURNS_ACCEPTED = "returnsAccepted";
  @SerializedName(SERIALIZED_NAME_RETURNS_ACCEPTED)
  private Boolean returnsAccepted;

  public static final String SERIALIZED_NAME_RETURN_SHIPPING_COST_PAYER = "returnShippingCostPayer";
  @SerializedName(SERIALIZED_NAME_RETURN_SHIPPING_COST_PAYER)
  private String returnShippingCostPayer;


  public ReturnPolicy categoryTypes(List<CategoryType> categoryTypes) {
    
    this.categoryTypes = categoryTypes;
    return this;
  }

  public ReturnPolicy addCategoryTypesItem(CategoryType categoryTypesItem) {
    if (this.categoryTypes == null) {
      this.categoryTypes = new ArrayList<CategoryType>();
    }
    this.categoryTypes.add(categoryTypesItem);
    return this;
  }

   /**
   * This container indicates which category group that the return policy applies to.&lt;br/&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;b&gt;Note&lt;/b&gt;: Return business policies are not applicable to motor vehicle listings, so the &lt;b&gt;categoryTypes.name&lt;/b&gt; value will always be &lt;code&gt;ALL_EXCLUDING_MOTORS_VEHICLES&lt;/code&gt; for return business policies.&lt;/span&gt;
   * @return categoryTypes
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "This container indicates which category group that the return policy applies to.<br/><br/><span class=\"tablenote\"><b>Note</b>: Return business policies are not applicable to motor vehicle listings, so the <b>categoryTypes.name</b> value will always be <code>ALL_EXCLUDING_MOTORS_VEHICLES</code> for return business policies.</span>")

  public List<CategoryType> getCategoryTypes() {
    return categoryTypes;
  }


  public void setCategoryTypes(List<CategoryType> categoryTypes) {
    this.categoryTypes = categoryTypes;
  }


  public ReturnPolicy description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A seller-defined description of the return business policy. This description is only for the seller&#39;s use, and is not exposed on any eBay pages.  &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Max length&lt;/b&gt;: 250
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A seller-defined description of the return business policy. This description is only for the seller's use, and is not exposed on any eBay pages.  <br/><br/><b>Max length</b>: 250")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public ReturnPolicy extendedHolidayReturnsOffered(Boolean extendedHolidayReturnsOffered) {
    
    this.extendedHolidayReturnsOffered = extendedHolidayReturnsOffered;
    return this;
  }

   /**
   * &lt;p class&#x3D;\&quot;tablenote\&quot;&gt;&lt;span  style&#x3D;\&quot;color: #dd1e31;\&quot;&gt;&lt;b&gt;Important!&lt;/b&gt;&lt;/span&gt; This field is deprecated, since eBay no longer supports extended holiday returns. Any value supplied in this field is neither read nor returned.&lt;/p&gt; 
   * @return extendedHolidayReturnsOffered
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<p class=\"tablenote\"><span  style=\"color: #dd1e31;\"><b>Important!</b></span> This field is deprecated, since eBay no longer supports extended holiday returns. Any value supplied in this field is neither read nor returned.</p> ")

  public Boolean getExtendedHolidayReturnsOffered() {
    return extendedHolidayReturnsOffered;
  }


  public void setExtendedHolidayReturnsOffered(Boolean extendedHolidayReturnsOffered) {
    this.extendedHolidayReturnsOffered = extendedHolidayReturnsOffered;
  }


  public ReturnPolicy internationalOverride(InternationalReturnOverrideType internationalOverride) {
    
    this.internationalOverride = internationalOverride;
    return this;
  }

   /**
   * Get internationalOverride
   * @return internationalOverride
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public InternationalReturnOverrideType getInternationalOverride() {
    return internationalOverride;
  }


  public void setInternationalOverride(InternationalReturnOverrideType internationalOverride) {
    this.internationalOverride = internationalOverride;
  }


  public ReturnPolicy marketplaceId(String marketplaceId) {
    
    this.marketplaceId = marketplaceId;
    return this;
  }

   /**
   * The ID of the eBay marketplace to which this return business policy applies. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return marketplaceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the eBay marketplace to which this return business policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>")

  public String getMarketplaceId() {
    return marketplaceId;
  }


  public void setMarketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
  }


  public ReturnPolicy name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * A seller-defined name for this payment business policy. Names must be unique for policies assigned to the same marketplace.&lt;br /&gt;&lt;br /&gt;&lt;b&gt;Max length:&lt;/b&gt; 64
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A seller-defined name for this payment business policy. Names must be unique for policies assigned to the same marketplace.<br /><br /><b>Max length:</b> 64")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public ReturnPolicy refundMethod(String refundMethod) {
    
    this.refundMethod = refundMethod;
    return this;
  }

   /**
   * This value indicates the refund method that will be used by the seller for buyer returns. In most cases, this value is going to be &lt;code&gt;MONEY_BACK&lt;/code&gt;, except for &#39;Click and Collect&#39; and &#39;Buy Online, Pick up in Store&#39; orders where the seller is able to offer a store/merchandise credit in addition to the &#39;money back&#39; option. The buyer recieving money back for a return is always an option available to the buyer, even if this field returns &lt;code&gt;MERCHANDISE_CREDIT&lt;/code&gt;. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/account/types/api:RefundMethodEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return refundMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This value indicates the refund method that will be used by the seller for buyer returns. In most cases, this value is going to be <code>MONEY_BACK</code>, except for 'Click and Collect' and 'Buy Online, Pick up in Store' orders where the seller is able to offer a store/merchandise credit in addition to the 'money back' option. The buyer recieving money back for a return is always an option available to the buyer, even if this field returns <code>MERCHANDISE_CREDIT</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:RefundMethodEnum'>eBay API documentation</a>")

  public String getRefundMethod() {
    return refundMethod;
  }


  public void setRefundMethod(String refundMethod) {
    this.refundMethod = refundMethod;
  }


  public ReturnPolicy restockingFeePercentage(String restockingFeePercentage) {
    
    this.restockingFeePercentage = restockingFeePercentage;
    return this;
  }

   /**
   * &lt;p class&#x3D;\&quot;tablenote\&quot;&gt;&lt;span  style&#x3D;\&quot;color: #dd1e31;\&quot;&gt;&lt;b&gt;Important!&lt;/b&gt;&lt;/span&gt; This field is deprecated, since eBay no longer allows sellers to charge a restocking fee for buyer remorse returns. If this field is included, it is ignored and it is no longer returned.&lt;/p&gt;
   * @return restockingFeePercentage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "<p class=\"tablenote\"><span  style=\"color: #dd1e31;\"><b>Important!</b></span> This field is deprecated, since eBay no longer allows sellers to charge a restocking fee for buyer remorse returns. If this field is included, it is ignored and it is no longer returned.</p>")

  public String getRestockingFeePercentage() {
    return restockingFeePercentage;
  }


  public void setRestockingFeePercentage(String restockingFeePercentage) {
    this.restockingFeePercentage = restockingFeePercentage;
  }


  public ReturnPolicy returnInstructions(String returnInstructions) {
    
    this.returnInstructions = returnInstructions;
    return this;
  }

   /**
   * This text-based field provides more details on seller-specified return instructions. This field is only returned if set for the return business policy. &lt;p class&#x3D;\&quot;tablenote\&quot;&gt;&lt;span  style&#x3D;\&quot;color: #dd1e31;\&quot;&gt;&lt;b&gt;Important!&lt;/b&gt;&lt;/span&gt; This field is no longer supported on many eBay marketplaces. To see if a marketplace and eBay category does support this field, call &lt;a href&#x3D;\&quot;/api-docs/sell/metadata/resources/marketplace/methods/getReturnPolicies\&quot;&gt;getReturnPolicies&lt;/a&gt; method of the &lt;b&gt;Metadata API&lt;/b&gt;. Then you will look for the &lt;b&gt;policyDescriptionEnabled&lt;/b&gt; field with a value of &lt;code&gt;true&lt;/code&gt; for the eBay category.&lt;/span&gt;&lt;/p&gt;&lt;br/&gt;&lt;b&gt;Max length&lt;/b&gt;: 5000 (8000 for DE)
   * @return returnInstructions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This text-based field provides more details on seller-specified return instructions. This field is only returned if set for the return business policy. <p class=\"tablenote\"><span  style=\"color: #dd1e31;\"><b>Important!</b></span> This field is no longer supported on many eBay marketplaces. To see if a marketplace and eBay category does support this field, call <a href=\"/api-docs/sell/metadata/resources/marketplace/methods/getReturnPolicies\">getReturnPolicies</a> method of the <b>Metadata API</b>. Then you will look for the <b>policyDescriptionEnabled</b> field with a value of <code>true</code> for the eBay category.</span></p><br/><b>Max length</b>: 5000 (8000 for DE)")

  public String getReturnInstructions() {
    return returnInstructions;
  }


  public void setReturnInstructions(String returnInstructions) {
    this.returnInstructions = returnInstructions;
  }


  public ReturnPolicy returnMethod(String returnMethod) {
    
    this.returnMethod = returnMethod;
    return this;
  }

   /**
   * This field is only returned if the seller wants to offer an alternative return method other than &#39;money back&#39;, such as an exchange or replacement item. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/account/types/api:ReturnMethodEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return returnMethod
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This field is only returned if the seller wants to offer an alternative return method other than 'money back', such as an exchange or replacement item. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ReturnMethodEnum'>eBay API documentation</a>")

  public String getReturnMethod() {
    return returnMethod;
  }


  public void setReturnMethod(String returnMethod) {
    this.returnMethod = returnMethod;
  }


  public ReturnPolicy returnPeriod(TimeDuration returnPeriod) {
    
    this.returnPeriod = returnPeriod;
    return this;
  }

   /**
   * Get returnPeriod
   * @return returnPeriod
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public TimeDuration getReturnPeriod() {
    return returnPeriod;
  }


  public void setReturnPeriod(TimeDuration returnPeriod) {
    this.returnPeriod = returnPeriod;
  }


  public ReturnPolicy returnPolicyId(String returnPolicyId) {
    
    this.returnPolicyId = returnPolicyId;
    return this;
  }

   /**
   * A unique eBay-assigned ID for a return business policy. This ID is generated when the policy is created.
   * @return returnPolicyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A unique eBay-assigned ID for a return business policy. This ID is generated when the policy is created.")

  public String getReturnPolicyId() {
    return returnPolicyId;
  }


  public void setReturnPolicyId(String returnPolicyId) {
    this.returnPolicyId = returnPolicyId;
  }


  public ReturnPolicy returnsAccepted(Boolean returnsAccepted) {
    
    this.returnsAccepted = returnsAccepted;
    return this;
  }

   /**
   * If this field is returned as &lt;code&gt;true&lt;/code&gt;, the seller accepts returns. &lt;br/&gt;&lt;br/&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;strong&gt;Note:&lt;/strong&gt;Top-Rated sellers must accept item returns and the &lt;b&gt;handlingTime&lt;/b&gt; should be set to zero days or one day for a listing to receive a Top-Rated Plus badge on the View Item or search result pages. For more information on eBay&#39;s Top-Rated seller program, see &lt;a href&#x3D;\&quot;https://pages.ebay.com/help/sell/top-rated.html\&quot;&gt;Becoming a Top Rated Seller and qualifying for Top Rated Plus benefits&lt;/a&gt;.&lt;/span&gt;
   * @return returnsAccepted
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If this field is returned as <code>true</code>, the seller accepts returns. <br/><br/><span class=\"tablenote\"><strong>Note:</strong>Top-Rated sellers must accept item returns and the <b>handlingTime</b> should be set to zero days or one day for a listing to receive a Top-Rated Plus badge on the View Item or search result pages. For more information on eBay's Top-Rated seller program, see <a href=\"https://pages.ebay.com/help/sell/top-rated.html\">Becoming a Top Rated Seller and qualifying for Top Rated Plus benefits</a>.</span>")

  public Boolean getReturnsAccepted() {
    return returnsAccepted;
  }


  public void setReturnsAccepted(Boolean returnsAccepted) {
    this.returnsAccepted = returnsAccepted;
  }


  public ReturnPolicy returnShippingCostPayer(String returnShippingCostPayer) {
    
    this.returnShippingCostPayer = returnShippingCostPayer;
    return this;
  }

   /**
   * This field indicates who is responsible for paying for the shipping charges for returned items. The field can be set to either &lt;code&gt;BUYER&lt;/code&gt; or &lt;code&gt;SELLER&lt;/code&gt;.  &lt;br/&gt;&lt;br/&gt;Depending on the return policy and specifics of the return, either the buyer or the seller can be responsible for the return shipping costs. Note that the seller is always responsible for return shipping costs for SNAD-related issues. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/account/types/api:ReturnShippingCostPayerEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return returnShippingCostPayer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "This field indicates who is responsible for paying for the shipping charges for returned items. The field can be set to either <code>BUYER</code> or <code>SELLER</code>.  <br/><br/>Depending on the return policy and specifics of the return, either the buyer or the seller can be responsible for the return shipping costs. Note that the seller is always responsible for return shipping costs for SNAD-related issues. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/api:ReturnShippingCostPayerEnum'>eBay API documentation</a>")

  public String getReturnShippingCostPayer() {
    return returnShippingCostPayer;
  }


  public void setReturnShippingCostPayer(String returnShippingCostPayer) {
    this.returnShippingCostPayer = returnShippingCostPayer;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReturnPolicy returnPolicy = (ReturnPolicy) o;
    return Objects.equals(this.categoryTypes, returnPolicy.categoryTypes) &&
        Objects.equals(this.description, returnPolicy.description) &&
        Objects.equals(this.extendedHolidayReturnsOffered, returnPolicy.extendedHolidayReturnsOffered) &&
        Objects.equals(this.internationalOverride, returnPolicy.internationalOverride) &&
        Objects.equals(this.marketplaceId, returnPolicy.marketplaceId) &&
        Objects.equals(this.name, returnPolicy.name) &&
        Objects.equals(this.refundMethod, returnPolicy.refundMethod) &&
        Objects.equals(this.restockingFeePercentage, returnPolicy.restockingFeePercentage) &&
        Objects.equals(this.returnInstructions, returnPolicy.returnInstructions) &&
        Objects.equals(this.returnMethod, returnPolicy.returnMethod) &&
        Objects.equals(this.returnPeriod, returnPolicy.returnPeriod) &&
        Objects.equals(this.returnPolicyId, returnPolicy.returnPolicyId) &&
        Objects.equals(this.returnsAccepted, returnPolicy.returnsAccepted) &&
        Objects.equals(this.returnShippingCostPayer, returnPolicy.returnShippingCostPayer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryTypes, description, extendedHolidayReturnsOffered, internationalOverride, marketplaceId, name, refundMethod, restockingFeePercentage, returnInstructions, returnMethod, returnPeriod, returnPolicyId, returnsAccepted, returnShippingCostPayer);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReturnPolicy {\n");
    sb.append("    categoryTypes: ").append(toIndentedString(categoryTypes)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    extendedHolidayReturnsOffered: ").append(toIndentedString(extendedHolidayReturnsOffered)).append("\n");
    sb.append("    internationalOverride: ").append(toIndentedString(internationalOverride)).append("\n");
    sb.append("    marketplaceId: ").append(toIndentedString(marketplaceId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    refundMethod: ").append(toIndentedString(refundMethod)).append("\n");
    sb.append("    restockingFeePercentage: ").append(toIndentedString(restockingFeePercentage)).append("\n");
    sb.append("    returnInstructions: ").append(toIndentedString(returnInstructions)).append("\n");
    sb.append("    returnMethod: ").append(toIndentedString(returnMethod)).append("\n");
    sb.append("    returnPeriod: ").append(toIndentedString(returnPeriod)).append("\n");
    sb.append("    returnPolicyId: ").append(toIndentedString(returnPolicyId)).append("\n");
    sb.append("    returnsAccepted: ").append(toIndentedString(returnsAccepted)).append("\n");
    sb.append("    returnShippingCostPayer: ").append(toIndentedString(returnShippingCostPayer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

