/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.CategoryType;
import com.nextop.ebay.client.model.Error;
import com.nextop.ebay.client.model.RegionSet;
import com.nextop.ebay.client.model.ShippingOption;
import com.nextop.ebay.client.model.TimeDuration;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Complex type that that gets populated with a response containing a fulfillment policy.
 */
@ApiModel(description = "Complex type that that gets populated with a response containing a fulfillment policy.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class SetFulfillmentPolicyResponse implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CATEGORY_TYPES = "categoryTypes";
  @SerializedName(SERIALIZED_NAME_CATEGORY_TYPES)
  private List<CategoryType> categoryTypes = null;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_FREIGHT_SHIPPING = "freightShipping";
  @SerializedName(SERIALIZED_NAME_FREIGHT_SHIPPING)
  private Boolean freightShipping;

  public static final String SERIALIZED_NAME_FULFILLMENT_POLICY_ID = "fulfillmentPolicyId";
  @SerializedName(SERIALIZED_NAME_FULFILLMENT_POLICY_ID)
  private String fulfillmentPolicyId;

  public static final String SERIALIZED_NAME_GLOBAL_SHIPPING = "globalShipping";
  @SerializedName(SERIALIZED_NAME_GLOBAL_SHIPPING)
  private Boolean globalShipping;

  public static final String SERIALIZED_NAME_HANDLING_TIME = "handlingTime";
  @SerializedName(SERIALIZED_NAME_HANDLING_TIME)
  private TimeDuration handlingTime;

  public static final String SERIALIZED_NAME_LOCAL_PICKUP = "localPickup";
  @SerializedName(SERIALIZED_NAME_LOCAL_PICKUP)
  private Boolean localPickup;

  public static final String SERIALIZED_NAME_MARKETPLACE_ID = "marketplaceId";
  @SerializedName(SERIALIZED_NAME_MARKETPLACE_ID)
  private String marketplaceId;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_PICKUP_DROP_OFF = "pickupDropOff";
  @SerializedName(SERIALIZED_NAME_PICKUP_DROP_OFF)
  private Boolean pickupDropOff;

  public static final String SERIALIZED_NAME_SHIPPING_OPTIONS = "shippingOptions";
  @SerializedName(SERIALIZED_NAME_SHIPPING_OPTIONS)
  private List<ShippingOption> shippingOptions = null;

  public static final String SERIALIZED_NAME_SHIP_TO_LOCATIONS = "shipToLocations";
  @SerializedName(SERIALIZED_NAME_SHIP_TO_LOCATIONS)
  private RegionSet shipToLocations;

  public static final String SERIALIZED_NAME_WARNINGS = "warnings";
  @SerializedName(SERIALIZED_NAME_WARNINGS)
  private List<Error> warnings = null;


  public SetFulfillmentPolicyResponse categoryTypes(List<CategoryType> categoryTypes) {
    
    this.categoryTypes = categoryTypes;
    return this;
  }

  public SetFulfillmentPolicyResponse addCategoryTypesItem(CategoryType categoryTypesItem) {
    if (this.categoryTypes == null) {
      this.categoryTypes = new ArrayList<CategoryType>();
    }
    this.categoryTypes.add(categoryTypesItem);
    return this;
  }

   /**
   * This container indicates whether the fulfillment business policy applies to motor vehicle listings, or if it applies to non-motor vehicle listings.
   * @return categoryTypes
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "This container indicates whether the fulfillment business policy applies to motor vehicle listings, or if it applies to non-motor vehicle listings.")

  public List<CategoryType> getCategoryTypes() {
    return categoryTypes;
  }


  public void setCategoryTypes(List<CategoryType> categoryTypes) {
    this.categoryTypes = categoryTypes;
  }


  public SetFulfillmentPolicyResponse description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * A seller-defined description of the fulfillment policy. This description is only for the seller&#39;s use, and is not exposed on any eBay pages. This field is returned if set for the policy. &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Max length&lt;/b&gt;: 250
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A seller-defined description of the fulfillment policy. This description is only for the seller's use, and is not exposed on any eBay pages. This field is returned if set for the policy. <br/><br/><b>Max length</b>: 250")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public SetFulfillmentPolicyResponse freightShipping(Boolean freightShipping) {
    
    this.freightShipping = freightShipping;
    return this;
  }

   /**
   * If returned as &lt;code&gt;true&lt;/code&gt;, the seller offers freight shipping. Freight shipping can be used for large items over 150 lbs.
   * @return freightShipping
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If returned as <code>true</code>, the seller offers freight shipping. Freight shipping can be used for large items over 150 lbs.")

  public Boolean getFreightShipping() {
    return freightShipping;
  }


  public void setFreightShipping(Boolean freightShipping) {
    this.freightShipping = freightShipping;
  }


  public SetFulfillmentPolicyResponse fulfillmentPolicyId(String fulfillmentPolicyId) {
    
    this.fulfillmentPolicyId = fulfillmentPolicyId;
    return this;
  }

   /**
   * A unique eBay-assigned ID for a fulfillment business policy. This ID is generated when the policy is created.
   * @return fulfillmentPolicyId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A unique eBay-assigned ID for a fulfillment business policy. This ID is generated when the policy is created.")

  public String getFulfillmentPolicyId() {
    return fulfillmentPolicyId;
  }


  public void setFulfillmentPolicyId(String fulfillmentPolicyId) {
    this.fulfillmentPolicyId = fulfillmentPolicyId;
  }


  public SetFulfillmentPolicyResponse globalShipping(Boolean globalShipping) {
    
    this.globalShipping = globalShipping;
    return this;
  }

   /**
   * If returned as &lt;code&gt;true&lt;/code&gt;, the eBay Global Shipping Program will be used by the seller to ship items to international locations.&lt;br /&gt;&lt;br /&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;b&gt;Note&lt;/b&gt;: On the US marketplace, the &lt;em&gt;&lt;b&gt;Global Shipping Program&lt;/b&gt;&lt;/em&gt; is scheduled to be replaced by a new intermediated international shipping program called &lt;em&gt;&lt;b&gt;eBay International Shipping&lt;/b&gt;&lt;/em&gt;. US sellers who are opted in to the Global Shipping Program will be automatically opted in to eBay International Shipping when it becomes available to them. All US sellers will be migrated by March 31, 2023. &lt;br /&gt;&lt;br /&gt;eBay International Shipping is an account level setting, and no field needs to be set in a Fulfillment business policy to enable it. As long as the US seller&#39;s account is opted in to eBay International Shipping, this shipping option will be enabled automatically for all listings where international shipping is available. A US seller who is opted in to eBay International Shipping can also specify individual international shipping service options for a Fulfillment business policy.&lt;/span&gt;
   * @return globalShipping
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If returned as <code>true</code>, the eBay Global Shipping Program will be used by the seller to ship items to international locations.<br /><br /><span class=\"tablenote\"><b>Note</b>: On the US marketplace, the <em><b>Global Shipping Program</b></em> is scheduled to be replaced by a new intermediated international shipping program called <em><b>eBay International Shipping</b></em>. US sellers who are opted in to the Global Shipping Program will be automatically opted in to eBay International Shipping when it becomes available to them. All US sellers will be migrated by March 31, 2023. <br /><br />eBay International Shipping is an account level setting, and no field needs to be set in a Fulfillment business policy to enable it. As long as the US seller's account is opted in to eBay International Shipping, this shipping option will be enabled automatically for all listings where international shipping is available. A US seller who is opted in to eBay International Shipping can also specify individual international shipping service options for a Fulfillment business policy.</span>")

  public Boolean getGlobalShipping() {
    return globalShipping;
  }


  public void setGlobalShipping(Boolean globalShipping) {
    this.globalShipping = globalShipping;
  }


  public SetFulfillmentPolicyResponse handlingTime(TimeDuration handlingTime) {
    
    this.handlingTime = handlingTime;
    return this;
  }

   /**
   * Get handlingTime
   * @return handlingTime
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public TimeDuration getHandlingTime() {
    return handlingTime;
  }


  public void setHandlingTime(TimeDuration handlingTime) {
    this.handlingTime = handlingTime;
  }


  public SetFulfillmentPolicyResponse localPickup(Boolean localPickup) {
    
    this.localPickup = localPickup;
    return this;
  }

   /**
   * If returned as &lt;code&gt;true&lt;/code&gt;, local pickup is available for this policy.
   * @return localPickup
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If returned as <code>true</code>, local pickup is available for this policy.")

  public Boolean getLocalPickup() {
    return localPickup;
  }


  public void setLocalPickup(Boolean localPickup) {
    this.localPickup = localPickup;
  }


  public SetFulfillmentPolicyResponse marketplaceId(String marketplaceId) {
    
    this.marketplaceId = marketplaceId;
    return this;
  }

   /**
   * The ID of the eBay marketplace to which this fulfillment business policy applies. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return marketplaceId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ID of the eBay marketplace to which this fulfillment business policy applies. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/account/types/ba:MarketplaceIdEnum'>eBay API documentation</a>")

  public String getMarketplaceId() {
    return marketplaceId;
  }


  public void setMarketplaceId(String marketplaceId) {
    this.marketplaceId = marketplaceId;
  }


  public SetFulfillmentPolicyResponse name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * A seller-defined name for this fulfillment business policy. Names must be unique for policies assigned to the same marketplace. &lt;br/&gt;&lt;br/&gt;&lt;b&gt;Max length&lt;/b&gt;: 64
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "A seller-defined name for this fulfillment business policy. Names must be unique for policies assigned to the same marketplace. <br/><br/><b>Max length</b>: 64")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public SetFulfillmentPolicyResponse pickupDropOff(Boolean pickupDropOff) {
    
    this.pickupDropOff = pickupDropOff;
    return this;
  }

   /**
   * If returned as &lt;code&gt;true&lt;/code&gt;, the seller offers the \&quot;Click and Collect\&quot; option. &lt;br/&gt;&lt;br/&gt;Currently, \&quot;Click and Collect\&quot; is available only to large retail merchants the eBay AU and UK marketplaces.
   * @return pickupDropOff
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "If returned as <code>true</code>, the seller offers the \"Click and Collect\" option. <br/><br/>Currently, \"Click and Collect\" is available only to large retail merchants the eBay AU and UK marketplaces.")

  public Boolean getPickupDropOff() {
    return pickupDropOff;
  }


  public void setPickupDropOff(Boolean pickupDropOff) {
    this.pickupDropOff = pickupDropOff;
  }


  public SetFulfillmentPolicyResponse shippingOptions(List<ShippingOption> shippingOptions) {
    
    this.shippingOptions = shippingOptions;
    return this;
  }

  public SetFulfillmentPolicyResponse addShippingOptionsItem(ShippingOption shippingOptionsItem) {
    if (this.shippingOptions == null) {
      this.shippingOptions = new ArrayList<ShippingOption>();
    }
    this.shippingOptions.add(shippingOptionsItem);
    return this;
  }

   /**
   * This array is used to provide detailed information on the domestic and international shipping options available for the policy. A separate &lt;b&gt;ShippingOption&lt;/b&gt; object covers domestic shipping service options and international shipping service options (if the seller ships to international locations). The &lt;b&gt;optionType&lt;/b&gt; field indicates whether the &lt;b&gt;ShippingOption&lt;/b&gt; object applies to domestic or international shipping, and the &lt;b&gt;costType&lt;/b&gt; field indicates whether flat-rate shipping or calculated shipping will be used. &lt;p&gt;A separate &lt;b&gt;ShippingServices&lt;/b&gt; object is used to specify cost and other details for every available domestic and international shipping service option. &lt;/p&gt;
   * @return shippingOptions
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "This array is used to provide detailed information on the domestic and international shipping options available for the policy. A separate <b>ShippingOption</b> object covers domestic shipping service options and international shipping service options (if the seller ships to international locations). The <b>optionType</b> field indicates whether the <b>ShippingOption</b> object applies to domestic or international shipping, and the <b>costType</b> field indicates whether flat-rate shipping or calculated shipping will be used. <p>A separate <b>ShippingServices</b> object is used to specify cost and other details for every available domestic and international shipping service option. </p>")

  public List<ShippingOption> getShippingOptions() {
    return shippingOptions;
  }


  public void setShippingOptions(List<ShippingOption> shippingOptions) {
    this.shippingOptions = shippingOptions;
  }


  public SetFulfillmentPolicyResponse shipToLocations(RegionSet shipToLocations) {
    
    this.shipToLocations = shipToLocations;
    return this;
  }

   /**
   * Get shipToLocations
   * @return shipToLocations
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "")

  public RegionSet getShipToLocations() {
    return shipToLocations;
  }


  public void setShipToLocations(RegionSet shipToLocations) {
    this.shipToLocations = shipToLocations;
  }


  public SetFulfillmentPolicyResponse warnings(List<Error> warnings) {
    
    this.warnings = warnings;
    return this;
  }

  public SetFulfillmentPolicyResponse addWarningsItem(Error warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<Error>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

   /**
   * An array of one or more errors or warnings that were generated during the processing of the request. If there were no issues with the request, this array will return empty.
   * @return warnings
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "An array of one or more errors or warnings that were generated during the processing of the request. If there were no issues with the request, this array will return empty.")

  public List<Error> getWarnings() {
    return warnings;
  }


  public void setWarnings(List<Error> warnings) {
    this.warnings = warnings;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SetFulfillmentPolicyResponse setFulfillmentPolicyResponse = (SetFulfillmentPolicyResponse) o;
    return Objects.equals(this.categoryTypes, setFulfillmentPolicyResponse.categoryTypes) &&
        Objects.equals(this.description, setFulfillmentPolicyResponse.description) &&
        Objects.equals(this.freightShipping, setFulfillmentPolicyResponse.freightShipping) &&
        Objects.equals(this.fulfillmentPolicyId, setFulfillmentPolicyResponse.fulfillmentPolicyId) &&
        Objects.equals(this.globalShipping, setFulfillmentPolicyResponse.globalShipping) &&
        Objects.equals(this.handlingTime, setFulfillmentPolicyResponse.handlingTime) &&
        Objects.equals(this.localPickup, setFulfillmentPolicyResponse.localPickup) &&
        Objects.equals(this.marketplaceId, setFulfillmentPolicyResponse.marketplaceId) &&
        Objects.equals(this.name, setFulfillmentPolicyResponse.name) &&
        Objects.equals(this.pickupDropOff, setFulfillmentPolicyResponse.pickupDropOff) &&
        Objects.equals(this.shippingOptions, setFulfillmentPolicyResponse.shippingOptions) &&
        Objects.equals(this.shipToLocations, setFulfillmentPolicyResponse.shipToLocations) &&
        Objects.equals(this.warnings, setFulfillmentPolicyResponse.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(categoryTypes, description, freightShipping, fulfillmentPolicyId, globalShipping, handlingTime, localPickup, marketplaceId, name, pickupDropOff, shippingOptions, shipToLocations, warnings);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SetFulfillmentPolicyResponse {\n");
    sb.append("    categoryTypes: ").append(toIndentedString(categoryTypes)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    freightShipping: ").append(toIndentedString(freightShipping)).append("\n");
    sb.append("    fulfillmentPolicyId: ").append(toIndentedString(fulfillmentPolicyId)).append("\n");
    sb.append("    globalShipping: ").append(toIndentedString(globalShipping)).append("\n");
    sb.append("    handlingTime: ").append(toIndentedString(handlingTime)).append("\n");
    sb.append("    localPickup: ").append(toIndentedString(localPickup)).append("\n");
    sb.append("    marketplaceId: ").append(toIndentedString(marketplaceId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    pickupDropOff: ").append(toIndentedString(pickupDropOff)).append("\n");
    sb.append("    shippingOptions: ").append(toIndentedString(shippingOptions)).append("\n");
    sb.append("    shipToLocations: ").append(toIndentedString(shipToLocations)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

