/*
 * ebay官方api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.nextop.ebay.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.nextop.ebay.client.model.DynamicAdRatePreference;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * A type that defines the request fields used to update the ad rate strategy for a Promoted Listings ad campaign.
 */
@ApiModel(description = "A type that defines the request fields used to update the ad rate strategy for a Promoted Listings ad campaign.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-09-07T14:51:10.412+08:00[Asia/Shanghai]")
public class UpdateAdrateStrategyRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_AD_RATE_STRATEGY = "adRateStrategy";
  @SerializedName(SERIALIZED_NAME_AD_RATE_STRATEGY)
  private String adRateStrategy;

  public static final String SERIALIZED_NAME_BID_PERCENTAGE = "bidPercentage";
  @SerializedName(SERIALIZED_NAME_BID_PERCENTAGE)
  private String bidPercentage;

  public static final String SERIALIZED_NAME_DYNAMIC_AD_RATE_PREFERENCES = "dynamicAdRatePreferences";
  @SerializedName(SERIALIZED_NAME_DYNAMIC_AD_RATE_PREFERENCES)
  private List<DynamicAdRatePreference> dynamicAdRatePreferences = null;


  public UpdateAdrateStrategyRequest adRateStrategy(String adRateStrategy) {
    
    this.adRateStrategy = adRateStrategy;
    return this;
  }

   /**
   * The ad rate strategy that shall be applied to the campaign. For implementation help, refer to &lt;a href&#x3D;&#39;https://developer.ebay.com/api-docs/sell/marketing/types/pls:AdRateStrategyEnum&#39;&gt;eBay API documentation&lt;/a&gt;
   * @return adRateStrategy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The ad rate strategy that shall be applied to the campaign. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/marketing/types/pls:AdRateStrategyEnum'>eBay API documentation</a>")

  public String getAdRateStrategy() {
    return adRateStrategy;
  }


  public void setAdRateStrategy(String adRateStrategy) {
    this.adRateStrategy = adRateStrategy;
  }


  public UpdateAdrateStrategyRequest bidPercentage(String bidPercentage) {
    
    this.bidPercentage = bidPercentage;
    return this;
  }

   /**
   * The user-defined &lt;b&gt;bid percentage&lt;/b&gt; (also known as the &lt;i&gt;ad rate&lt;/i&gt;) sets the level that eBay increases the visibility in search results for the associated listing. The higher the &lt;b&gt;bidPercentage&lt;/b&gt; value, the more eBay promotes the listing.  &lt;br&gt;&lt;br&gt;The value specified here is also used to calculate the Promoted Listings fee. This percentage value is multiplied by the final sales price to determine the fee. &lt;br&gt;&lt;br&gt;The Promoted Listings fee is determined at the time the transaction completes and the seller is assessed the fee only when an item sells through a Promoted Listings ad campaign. &lt;br&gt;&lt;br&gt;The &lt;b&gt;bidPercentage&lt;/b&gt; is a single precision value that is guided by the following rules: &lt;ul&gt;&lt;li&gt;These values are &lt;b&gt;valid&lt;/b&gt;:&lt;br&gt;&amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;code&gt;4.1&lt;/code&gt;, &amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;code&gt;5.0&lt;/code&gt;, &amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;code&gt;5.5&lt;/code&gt;, ...&lt;/li&gt;  &lt;li&gt;These values are &lt;b&gt;not valid&lt;/b&gt;:&lt;br /&gt; &amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;code&gt;0.01&lt;/code&gt;, &amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;code&gt;10.75&lt;/code&gt;, &amp;nbsp;&amp;nbsp;&amp;nbsp;&lt;code&gt;99.99&lt;/code&gt;,&lt;br /&gt; &amp;nbsp;&amp;nbsp;&amp;nbsp;and so on.&lt;/li&gt;&lt;/ul&gt;This is the default bid percentage for the campaigns using the Cost Per Sale (CPS) funding model, and this value will be overridden by any ads in the campaign that have their own set bid percentages.&lt;br /&gt;&lt;br /&gt;If a bid percentage is not provided for an ad, eBay uses the default bid percentage of the associated campaign.&lt;br /&gt;&lt;br /&gt;&lt;b&gt;Minimum value:&lt;/b&gt; 2.0 &lt;br&gt;&lt;b&gt;Maximum value:&lt;/b&gt; 100.0
   * @return bidPercentage
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The user-defined <b>bid percentage</b> (also known as the <i>ad rate</i>) sets the level that eBay increases the visibility in search results for the associated listing. The higher the <b>bidPercentage</b> value, the more eBay promotes the listing.  <br><br>The value specified here is also used to calculate the Promoted Listings fee. This percentage value is multiplied by the final sales price to determine the fee. <br><br>The Promoted Listings fee is determined at the time the transaction completes and the seller is assessed the fee only when an item sells through a Promoted Listings ad campaign. <br><br>The <b>bidPercentage</b> is a single precision value that is guided by the following rules: <ul><li>These values are <b>valid</b>:<br>&nbsp;&nbsp;&nbsp;<code>4.1</code>, &nbsp;&nbsp;&nbsp;<code>5.0</code>, &nbsp;&nbsp;&nbsp;<code>5.5</code>, ...</li>  <li>These values are <b>not valid</b>:<br /> &nbsp;&nbsp;&nbsp;<code>0.01</code>, &nbsp;&nbsp;&nbsp;<code>10.75</code>, &nbsp;&nbsp;&nbsp;<code>99.99</code>,<br /> &nbsp;&nbsp;&nbsp;and so on.</li></ul>This is the default bid percentage for the campaigns using the Cost Per Sale (CPS) funding model, and this value will be overridden by any ads in the campaign that have their own set bid percentages.<br /><br />If a bid percentage is not provided for an ad, eBay uses the default bid percentage of the associated campaign.<br /><br /><b>Minimum value:</b> 2.0 <br><b>Maximum value:</b> 100.0")

  public String getBidPercentage() {
    return bidPercentage;
  }


  public void setBidPercentage(String bidPercentage) {
    this.bidPercentage = bidPercentage;
  }


  public UpdateAdrateStrategyRequest dynamicAdRatePreferences(List<DynamicAdRatePreference> dynamicAdRatePreferences) {
    
    this.dynamicAdRatePreferences = dynamicAdRatePreferences;
    return this;
  }

  public UpdateAdrateStrategyRequest addDynamicAdRatePreferencesItem(DynamicAdRatePreference dynamicAdRatePreferencesItem) {
    if (this.dynamicAdRatePreferences == null) {
      this.dynamicAdRatePreferences = new ArrayList<DynamicAdRatePreference>();
    }
    this.dynamicAdRatePreferences.add(dynamicAdRatePreferencesItem);
    return this;
  }

   /**
   * A field that indicates whether a single, user-defined bid percentage (also known as the &lt;i&gt;ad rate&lt;/i&gt;) should be used, or whether eBay should automatically adjust listings to maintain the daily suggested bid percentage.&lt;br /&gt;&lt;br /&gt;&lt;span class&#x3D;\&quot;tablenote\&quot;&gt;&lt;span style&#x3D;\&quot;color:#004680\&quot;&gt;&lt;strong&gt;Note:&lt;/strong&gt;&lt;/span&gt; Dynamic adjustment is only applicable when the &lt;b&gt;adRateStrategy&lt;/b&gt; is set to &lt;code&gt;DYNAMIC&lt;/code&gt;.&lt;/span&gt;&lt;br /&gt;&lt;b&gt;Default:&lt;/b&gt; &lt;code&gt;FIXED&lt;/code&gt;
   * @return dynamicAdRatePreferences
  **/
  @javax.annotation.Nullable
  @Valid
  @ApiModelProperty(value = "A field that indicates whether a single, user-defined bid percentage (also known as the <i>ad rate</i>) should be used, or whether eBay should automatically adjust listings to maintain the daily suggested bid percentage.<br /><br /><span class=\"tablenote\"><span style=\"color:#004680\"><strong>Note:</strong></span> Dynamic adjustment is only applicable when the <b>adRateStrategy</b> is set to <code>DYNAMIC</code>.</span><br /><b>Default:</b> <code>FIXED</code>")

  public List<DynamicAdRatePreference> getDynamicAdRatePreferences() {
    return dynamicAdRatePreferences;
  }


  public void setDynamicAdRatePreferences(List<DynamicAdRatePreference> dynamicAdRatePreferences) {
    this.dynamicAdRatePreferences = dynamicAdRatePreferences;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdateAdrateStrategyRequest updateAdrateStrategyRequest = (UpdateAdrateStrategyRequest) o;
    return Objects.equals(this.adRateStrategy, updateAdrateStrategyRequest.adRateStrategy) &&
        Objects.equals(this.bidPercentage, updateAdrateStrategyRequest.bidPercentage) &&
        Objects.equals(this.dynamicAdRatePreferences, updateAdrateStrategyRequest.dynamicAdRatePreferences);
  }

  @Override
  public int hashCode() {
    return Objects.hash(adRateStrategy, bidPercentage, dynamicAdRatePreferences);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdateAdrateStrategyRequest {\n");
    sb.append("    adRateStrategy: ").append(toIndentedString(adRateStrategy)).append("\n");
    sb.append("    bidPercentage: ").append(toIndentedString(bidPercentage)).append("\n");
    sb.append("    dynamicAdRatePreferences: ").append(toIndentedString(dynamicAdRatePreferences)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

